// client/src/app/keyword-list-items/keyword-list-items.component.ts
import { Component, OnInit, ViewChildren, QueryList, ElementRef } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { KeywordService } from '../services/keyword.service';
import { KeywordListItemModel } from '../models/keyword-list-item';
import { KeywordListModel } from '../models/keyword-list';

@Component({
  selector: 'app-keyword-list-items',
  templateUrl: './keyword-list-items.component.html',
  styleUrls: ['./keyword-list-items.component.scss']
})
export class KeywordListItemsComponent implements OnInit {
  keywordListID: any;
  keywordList: any;
  keywordListItems: any[];
  validName = true;
  newPressed = false;

  @ViewChildren('keywordInput') set newInput(inputs: QueryList<ElementRef>) {
    if (inputs) {
      if (this.newPressed) {
        setTimeout(() => {
          inputs.last.nativeElement.focus();
          this.newPressed = false;
        }, 0);
      }
    }
  }

  constructor(private router: Router,
              private route: ActivatedRoute,
              private keywordService: KeywordService) { }

  ngOnInit() {
    this.route.params.subscribe(params => {
      const url = this.router.url;
      this.keywordListID = params['keyword-list-id'];
      if (!isNaN(this.keywordListID)) {
        this.keywordService.getKeywordList(this.keywordListID).subscribe(result => {
          this.keywordList = result;
          this.keywordListItems = [];
          for (const keyword of this.keywordList.keywords) {
            this.keywordListItems.push({'keyword': keyword});
          }
        });
      } else {
        this.keywordListID = -1; // -1 denotes that list is new
        this.keywordList = new KeywordListModel();
        this.keywordList.name = null;
        this.keywordList.id = -1;
        this.keywordListItems = [];
      }
    });
  }

  saveKeywordList() {
    if (!this.isValid) {
      return;
    }
    const keywords = this.keywordListItems.filter(item => item.keyword != null).map(item => item.keyword);
    if (this.keywordListID === -1) {
      this.keywordService.createKeywordList(this.keywordList.name, keywords).subscribe(response => {
        this.goBackToKeywordLists();
      }, error => {
        alert(error.json()['message']);
      });
    } else {
      this.keywordService.updateKeywordList(this.keywordListID, this.keywordList.name, keywords).subscribe(response => {
        this.goBackToKeywordLists();
      }, error => {
        alert(error.json()['message']);
      });
    }
  }

  addNewKeyword() {
    const emptyItems = this.keywordListItems.filter(item => !item.keyword);
    for (const emptyItem of emptyItems) {
      this.removeKeyword(emptyItem);
    }
    this.newPressed = true;
    this.keywordListItems.push(new KeywordListItemModel());
  }

  removeKeyword(item) {
    this.keywordListItems = this.keywordListItems.filter(k => k !== item);
  }

  checkName(event: any) {
    // TBD: Set name rules.
    this.validName = true;
    if (this.validName) {
      if (event.which === 13) { // Enter
        this.addNewKeyword();
      }
    }
  }

  checkKeyword(keyword: any, event: any) {
    if (!keyword.keyword) {
      return;
    }
    const new_keyword = keyword.keyword.trim().toLowerCase();
    if (new_keyword.length === 0) {
      keyword.error = 'Your keyword is empty.';
    } else if (!new_keyword.match('^[A-Za-z0-9\']+$')) {
      keyword.error = 'Your keyword contains one or more invalid characters. Please only use alphabets and numbers.'
                    + ' Spaces and special characters are not allowed.';
    } else if (this.keywordListItems.find(k => k.keyword === keyword.keyword && k !== keyword)) {
      keyword.error = 'Your list already contains that keyword.';
    } else {
      keyword.error = null;
    }
    if (!keyword.error) {
      if (event.which === 13) { // Enter
        this.addNewKeyword();
      }
    }
  }

  trackByFn(index, item) {
    return item.value;
  }

  get isValid(): boolean {
    if (this.keywordList && this.keywordListItems && this.keywordListItems.length !== 0) {
      return (this.validName && this.keywordListItems.filter(k => k.error != null).length === 0
      && this.keywordListItems.filter(k => k.keyword && k.keyword.length !== 0).length > 0);
    }
    return false;
  }

  goBackToKeywordLists() {
    this.router.navigate(['/keyword-lists']);
  }
}

<div class="container">
  <app-header [leftText]="'Cancel'" [rightText]="'Save'" [title]="'Edit Keywords'" [rightEnabled]="isValid" (backClick)="goBackToKeywordLists()" (rightTextClick)="saveKeywordList()"></app-header>
  <ng-container *ngIf="keywordList && keywordListItems">
    <div class="load-text onload" *ngIf="!keywordList">Loading...</div>
    <div class="empty-keyword-list" *ngIf="keywordListItems && keywordListItems.length == 0">
      <div class="load-text">Type a title for your list and click Add Keyword below to add keywords.</div>
    </div>
    <input class="keyword-lists-title" placeholder="Enter new list name" type="text" [(ngModel)]="keywordList.name" (keyup)="checkName($event)" maxlength=64>
    <div class="keyword-lists-container">
      <div *ngFor="let keyword of keywordListItems; trackBy: trackByFn" class="change-keywords-container">
        <input #keywordInput touched=true type="text" [(ngModel)]="keyword.keyword" autocomplete="off" (keyup)="checkKeyword(keyword, $event)" maxlength=64>
        <img width=16 height=16 src="../../assets/img/remove.svg" (click)="removeKeyword(keyword)">
        <div *ngIf="keyword.error" class="add-new-keywords-status">{{keyword.error}}</div>
      </div>
    </div>
    <button class="basic-button medium-button"(click)="addNewKeyword()">Add Keyword</button>
  </ng-container>
</div>

// frontend/src/keyword-list-items/keyword-list-items-component.jsx
import { KeywordService } from '../services/keyword-service';
import { KeywordListItemModel } from '../models/keyword-list-item';
import { KeywordListModel } from '../models/keyword-list';
import { useEffect, useState } from 'react';
import { useNavigate, useParams, useLocation } from 'react-router-dom';
import { KeywordListPages } from './html-pages'


function KeywordListItemsComponent() {

  const [keywordList, setKeywordList] = useState([]);
  const [keywordListItems, setKeywordListItems] = useState([]);
  const [validName, setValidName] = useState(false);
  const [newPressed, setNewPressed] = useState(false);
  const { keyword_list_id } = useParams();
  const [keywordListID, setKeywordListID] = useState(keyword_list_id);
  const [keyworderror, setKeywordError] = useState("")
  const [changing, setChanging] = useState(false);
  const [trigger, setTrigger] = useState(0);
  const navigate = useNavigate();
  const location = useLocation();  

  useEffect(() => {
    if (keywordListID !== undefined && keywordListID !== '-1') {
      new KeywordService().getKeywordList(keywordListID).then(async response => {
        if (response.status === 200) {
          const data = response.json()
          data.then(
            succ => {
              const result = KeywordListModel.fromJson(succ);
              setKeywordList(result);
              setValidName(true)
            }
          )

        } else {
          console.error("Keyword-items-components func: useEffect 2 ", response)
        }
      },
        apierror => {
          console.error("Keyword-items-components func: useEffect 2 ", apierror)
        });
    } else {
      //console.log("i am inside else")
      setKeywordListID('-1'); // -1 denotes that list is new
      setKeywordList(new KeywordListModel());
      if (keywordList !== null) {
        keywordList.name = null;
        keywordList.id = -1;
      }
      setKeywordListItems([]);
    }
  }, [])

  useEffect(() => {
    if(keywordListID !== undefined && keywordListID !== '-1' && keywordList.length !== 0){
    const kwListItem = []
    for (const keyword of keywordList.keywords) {
      kwListItem.push({ 'keyword': keyword });
    }
    setKeywordListItems(kwListItem);
  }
  },[keywordList.length])
  
  useEffect(() => {
  },[trigger])
  

  
  // @ViewChildren('keywordInput') set newInput(inputs: QueryList<ElementRef>) {
  //   if (inputs) {
  //     if (this.newPressed) {
  //       setTimeout(() => {
  //         inputs.last.nativeElement.focus();
  //         this.newPressed = false;
  //       }, 0);
  //     }
  //   }
  // }


  const saveKeywordList = () => {
    if (!isValid()) {
      return;
    }
    const keywords = keywordListItems.filter(item => item.keyword != null).map(item => item.keyword);
    if (keywordListID === '-1') {
      new KeywordService().createKeywordList(keywordList.name, keywords).then(
        async response => {
          if (response.status === 200) {
            goBackToKeywordLists();
          } else {
            alert((await response.json())['message']);
          }
        },
        apierror => {
          console.error("Keyword-items-components func: saveKeywordList 2 ", apierror)
        });
    } else {
      new KeywordService().updateKeywordList(keywordListID, keywordList.name, keywords).then(
        async response => {
          if (response.status === 200) {
            goBackToKeywordLists();
          } else {
            alert((await response.json())['message']);
          }
        },
        apierror => {
          console.error("Keyword-items-components func: saveKeywordList 3 ", apierror)
        });
    }
  }

  const addNewKeyword = () => {
    const emptyItems = keywordListItems.filter(item => !item.keyword);
    for (const emptyItem of emptyItems) {
      removeKeyword(emptyItem);
    }
    setNewPressed(true);
    keywordListItems.push(new KeywordListItemModel());
    if (newPressed) {
      setTimeout(() => {
        setNewPressed(false);
      }, 0);
    }

  }

  const removeKeyword = (item) => {
    let keyItems = keywordListItems.filter(k => k !== item);
    setKeywordListItems(keyItems);
    setChanging(true);
    setTrigger(trigger + 1);
    setChanging(false);
    setTrigger(trigger + 1);
  }

  const checkName = (event) => {
    // TBD: Set name rules.
    keywordList.name = event.target.value
    setValidName(true);
    if (validName) {
      if (event.which === 13) { // Enter
        addNewKeyword();
      }
    }
  }

  const checkKeyword = (keyword, event) => {
    keyword.keyword = event.target.value
    if (!keyword.keyword) {
      return;
    }
    const new_keyword = keyword.keyword.trim().toLowerCase();
    if (new_keyword.length === 0) {
      keyword.error = true
      setKeywordError('Your keyword is empty.');
    } else if (!new_keyword.match('^[A-Za-z0-9\u00C0-\u017F\']+$')) {
      keyword.error = true
      setKeywordError('Your keyword contains one or more invalid characters. Please only use alphabets and numbers.'
        + ' Spaces and special characters are not allowed.');
    } else if (keywordListItems.find(k => k.keyword === keyword.keyword && k !== keyword)) {
      keyword.error = true
      setKeywordError('Your list already contains that keyword.');
    } else {
      keyword.error = null
      setKeywordError("");
    }
    if (keyword.error === null && keyworderror === "") {
      if (event.which === 13) { // Enter
        addNewKeyword();
      }
    }
  }

  // const trackByFn = (index, item)=> {
  //   return item.value;
  // }

  const isValid = () => {
    let ret = false;
    if (keywordList && keywordListItems && keywordListItems.length !== 0) {
      ret = (validName && keywordListItems.filter(k => k.error != null).length === 0
        && keywordListItems.filter(k => k.keyword && k.keyword.length !== 0).length > 0);
    }

   
    return ret;
  }

  const goBackToKeywordLists = () => {
    if (location.pathname === '/keyword-lists/new-session') {
      //save keyword list too
      navigate('/sessions/new', {state: location.state});
    } else {
      navigate('/keyword-lists');
    }
  }
  
  return (
    <KeywordListPages
      navigate={goBackToKeywordLists}
      saveKeywordList={saveKeywordList}
      keywordListItems={keywordListItems}
      keywordList={keywordList}
      checkKeyword={checkKeyword}
      removeKeyword={removeKeyword}
      addNewKeyword={addNewKeyword}
      checkName={checkName}
      isValid={isValid()}
      keywordError={keyworderror}
      changing={changing}
    />
  )
}

export { KeywordListItemsComponent }
