// frontend/src/manage-keyword-lists/manage-keyword-lists-component.jsx
import { KeywordService } from "../services/keyword-service";
import { KeywordListModel } from '../models/keyword-list';
import { formatDate } from "../globals";
import { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { KeywordListPage } from './html-pages'


function ManageKeywordListsComponent(props) {
  const navigate = useNavigate();
  const [deleteDialogIsOpen, setDeleteDialogIsOpen] = useState(false);
  const [keywordListToDelete, setKeywordListToDelete] = useState(null);
  const [keywordLists, setKeywordLists] = useState([]);
  const [topics, setTopics] = useState([]);
  //const location = useLocation();

  const formatdate = formatDate; // Allows the HTML to invoke the function.

  useEffect(() => {
    const fetchData = new KeywordService().getKeywordLists();
    fetchData.then(
      (response) => {
        if (response.status === 200) {
          const resp = response.json()
          resp.then(
            (result) => {
              let keywordss = '';
              const kwordLists = KeywordListModel.fromJsonList(result)
              setKeywordLists(kwordLists)
              
            },
            (err) => { console.log('ManageKeywordListsComponent error func : useeffect 122' ,err) })

        } else {
          console.log('ManageKeywordListsComponent error func : useeffect 1', response)
        }
      },
      (apierror) => {
        console.log('ManageKeywordListsComponent error func : useeffect 2', apierror)
      }
    )
  }, []);

  //console.log(location.state, 'debugging ..')

  const openNewKeywordList = () => {
    return navigate('/keyword-lists/new');
  }
  
  const tempFunction = () => {
    //using this in place of createTopicModel now, seeing what happens
    console.log("Inside the function");
    //then try to change
    navigate("/file_upload");
  }
 

  const createTopicModel = () => {
    return navigate('/file_upload', { state: {fromManagedList: true}});
    // just in case the getTopics() function is made later
    const fetchData = new KeywordService().getTopics();
    fetchData.then(
      (response) => {
        if (response.status === 200) {
          setTopics(response.json())
          for (const topic of topics) {
            console.log("Topic: ", topic);
          }
        } else {
          console.log('ManageKeywordListsComponent error func : createTopicModel 1', response)
        }
      },
      (apierror) => {
        console.log('ManageKeywordListsComponent error func : createTopicModel 2', apierror)
      }
    )
  }

  const keywordListClicked = (keywordList) => {
    return navigate("/keyword-lists/" + keywordList.id);
  }

  const navigateToHomeScreen = () => {
    return navigate("/home");
  }

  const closeDeleteDialog = () => {
    setDeleteDialogIsOpen(false);
  }

  // Open confirmation dialog.
  const deleteKeywordList = (keywordList) => {
    setKeywordListToDelete(keywordList);
    setDeleteDialogIsOpen(true);
  }

  // Deletes a keyword list.  Called from confirmation dialog.
  const confirmDeleteKeywordList = () => {
    const fetchData = new KeywordService().deleteKeywordList(keywordListToDelete.id)
    fetchData.then(
      (result) => {
        const filtered = keywordLists.filter(
          (kl) => kl.id !== keywordListToDelete.id
        );
        setKeywordLists(filtered)
        setKeywordListToDelete(null);
        closeDeleteDialog();
      },
      (apierror) => {
        console.log("ManageKeywordListsComponent error func: confirmDeleteKeywordList, Failed to delete keyword list.", apierror);
        closeDeleteDialog();
      }
    );
  }

  // const formatKeywords = (keywords)=> {
  //   if (keywords) {
  //     return keywords.map((k) => k.keyword).join(", ");
  //   }
  //   return "";
  // }

  return (
    <KeywordListPage
      formatdate={formatdate}
      deleteDialogIsOpen={deleteDialogIsOpen}
      closeDeleteDialog={closeDeleteDialog}
      keywordLists={keywordLists}
      navigate={navigateToHomeScreen}
      keywordListClicked={keywordListClicked}
      deleteKeywordList={deleteKeywordList}
      openNewKeywordList={openNewKeywordList}
      createTopicModel={createTopicModel}
      confirmDeleteKeywordList={confirmDeleteKeywordList}
      tempFunction = {tempFunction}
    />
  )
}

export { ManageKeywordListsComponent }

// client/src/app/manage-keyword-lists/manage-keyword-lists.component.ts
import { Component, OnInit } from "@angular/core";
import { Router } from "@angular/router";
import { KeywordService } from "../services/keyword.service";
import { formatDate } from "../globals";

@Component({
  selector: "app-manage-keyword-lists",
  templateUrl: "./manage-keyword-lists.component.html",
  styleUrls: ["./manage-keyword-lists.component.scss"],
})
export class ManageKeywordListsComponent implements OnInit {
  constructor(private router: Router, private keywordService: KeywordService) {}

  deleteDialogIsOpen = false;
  keywordListToDelete: any;
  keywordLists: any[];
  topics: any[];
  formatDate = formatDate; // Allows the HTML to invoke the function.

  ngOnInit() {
    this.keywordService.getKeywordLists().subscribe((keywordLists) => {
      this.keywordLists = keywordLists;
      for (const keywordList of this.keywordLists) {
        keywordList["keywordsText"] = keywordList.keywords.join(", ");
      }
    });
  }

  openNewKeywordList() {
    this.router.navigate(["/keyword-lists/new"]);
  }

  createTopicModel() {
    this.keywordService.getTopics().subscribe((topics) => {
      this.topics = topics;
      for (const topic of this.topics) {
        console.log("Topic: ", topic);
      }
    });
  }

  keywordListClicked(keywordList) {
    this.router.navigate(["/keyword-lists/" + keywordList.id]);
  }

  navigateToHomeScreen() {
    this.router.navigate(["/homescreen"]);
  }

  closeDeleteDialog() {
    this.deleteDialogIsOpen = false;
  }

  // Open confirmation dialog.
  deleteKeywordList(keywordList) {
    this.keywordListToDelete = keywordList;
    this.deleteDialogIsOpen = true;
  }

  // Deletes a keyword list.  Called from confirmation dialog.
  confirmDeleteKeywordList() {
    this.keywordService
      .deleteKeywordList(this.keywordListToDelete.id)
      .subscribe(
        (result) => {
          this.keywordLists = this.keywordLists.filter(
            (kl) => kl.id !== this.keywordListToDelete.id
          );
          this.keywordListToDelete = null;
          this.closeDeleteDialog();
        },
        (err) => {
          console.log("Failed to delete keyword list.");
          this.closeDeleteDialog();
        }
      );
  }

  formatKeywords(keywords) {
    if (keywords) {
      return keywords.map((k) => k.keyword).join(", ");
    }
    return "";
  }
}

<div class="container" [class.dialog-blur]="deleteDialogIsOpen">
  <app-header [title]="'Manage Keyword Lists'" (backClick)="navigateToHomeScreen()"></app-header>

  <div class="list-container">
    <div *ngIf="!keywordLists" [ngClass]="{ 'loading': loading }" class="load-text onload">Loading...</div>
    <div *ngIf="keywordLists && keywordLists.length == 0" class="empty-keyword-list">
      <div class="load-text"> No Keyword Lists </div>
      <div class="load-text-description"> Tap the button below to make your first keyword list. </div>
    </div>
    <div *ngFor="let keywordList of keywordLists" class="keyword-list-button">
      <div class="click-mask" (click)="keywordListClicked(keywordList)"></div>
      <div class="keyword-list-header">
        <div class="title">{{keywordList.name}}</div>
        <div class="date">{{formatDate(keywordList.creation_date)}}</div>
      </div>
      <div class="keyword-list-keywords">{{keywordList.keywordsText}}</div>
      <app-context-menu class="keyword-list-options">
        <div class="menu-item red" (click)="deleteKeywordList(keywordList)">Delete</div>
      </app-context-menu>
    </div>
  </div>
  <button class="basic-button medium-button" (click)="openNewKeywordList()">New Keyword List</button>
  <button class="basic-button medium-button" (click)="createTopicModel()">Create Topic Model</button>
</div>

<app-dialog *ngIf="deleteDialogIsOpen" (closeDialog)="closeDeleteDialog()">
  <div class="dialog-window">
    <div class="dialog-heading">Delete Keyword List</div>
    <div class="dialog-body">Are you sure you want to permanently delete this keyword list?</div>
    <button class="delete-button" (click)="confirmDeleteKeywordList()">Delete</button>
    <button class="cancel-button" (click)="closeDeleteDialog()">Cancel</button>
  </div>
</app-dialog>
