// frontend/src/pods/pods-component.jsx
import { DeviceService } from '../services/device-service';
import { DeviceModel } from '../models/device';
import { AuthService } from '../services/auth-service';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {PodComponentPage} from './html-pages'


function PodsComponent(props){
  const BLINK_DELAY = 15000;
  const user = props.userdata
  const [loading, setLoading] = useState(false);
  const [devices,setDevices] = useState([]);
  const [currentForm, setCurrentForm] = useState("");
  const [selectedDevice, setSelectedDevice] = useState();
  const [statusText,setStatusText] = useState('  ');
  const navigate = useNavigate()

  
  useEffect(()=>{
    const fetchData = new DeviceService().getDevices(false, null, null, true)
    fetchData.then(
      response => {
        if (response == 200) {
          const resp2 = response.json()
          resp2.then(
            respdevices => {
              const deviceresult = DeviceModel.fromJsonList(respdevices)
              setDevices(deviceresult);
              for (const device of deviceresult) {
                device['blinking'] = false;
              }
            }
          )
        }
      },
      apierror => {
        console.log("pods-components func: useEffect 1 ", apierror)
      }
    )

    return ()=> {
      const blinkingDevices = devices.filter(p => p.blinking === true);
      for (const device of blinkingDevices) {
        const fetchData = new DeviceService().blinkPod(device.id, 'stop')
        fetchData.then(
          response=>{},
          apierror=>{console.log("pods-components func: useEffect 2 ", apierror)}
          )
      }
    }
  },[])

  

  const blinkPod = (device)=>{
    device.blinking = !device.blinking;
    if (device.blinking) {
      const fetchData = new DeviceService().blinkPod(device.id, 'start')
      fetchData.then(
        response=>{
          if(response.status === 200){
            device.timeout = setTimeout(() => {
              device.timeoutId = null;
              device.blinking = false;
            }, BLINK_DELAY);
          }
        },
        apierror=>{console.log("pods-components func: blinkpod 2 ", apierror)}
        )
    } else {
      this.deviceService.blinkPod(device.id, 'stop').subscribe(() => {
        if (device.timeoutId !== null) {
          clearTimeout(device.timeoutId);
          device.timeoutId = null;
        }
      });
    }
  }

  const openDialog = (form, device)=>{
    setCurrentForm(form);
    setSelectedDevice(device);
  }

  const closeDialog = ()=> {
    setCurrentForm("");
    setSelectedDevice(null);
    setStatusText('');
  }

  const addDevice = (macAddress)=>{
    macAddress = macAddress.trim();
    const fetchData = new DeviceService().addDevice(macAddress)
    fetchData.then(
      response=>{
        if(response.status === 200){
          const respJson = response.json()
          respJson.then(
            result => {
              const dev = DeviceModel.fromJson(result);
              devices.push(dev);
            }, error => {
              alert('Failed to add pod: ' + error.json()['message']);
            }
          )
        }
      },
      apierror=>{
        console.log("pods-component func : addDevice",apierror)
      }
    ).finally(
      ()=> closeDialog()
    )
  }

  const removeDevice = ()=> {
    const device = selectedDevice;
    const fetchData = new DeviceService().removeDevice(device.id)
    fetchData.then(
      response=>{
        if(response.status === 200){
          const respJson = response.json()
          respJson.then(
            result => {
              setDevices(devices.filter(d => d !== device));
            }, error => {alert(error.json()['message']);}
          )
        }
      },
      apierror=>{
        console.log("pods-component func : removeDevice",apierror)
      }
    ).finally(
      ()=> closeDialog()
    )
  }

  const renameDevice = (newName)=> {
    if (selectedDevice.name === newName) {
      setStatusText('No change detected.');
    } else {
      const deviceId = selectedDevice.id;
      const fetchData = new DeviceService().setDevice(deviceId, {'name': newName})
      fetchData.then(
        response=>{
          if(response.status === 200){
            const respJson = response.json()
            respJson.then(
              result => {
                const dev = DeviceModel.fromJson(result);
                const deviceIndex = devices.findIndex(s => s.id === dev.id);
                if (deviceIndex > -1) {
                  devices[deviceIndex].name = newName;
                }
              }, error => {
                alert(error.json()['message']);
              }
            )
          }
        },
        apierror=>{
          console.log("pods-component func : addDevice",apierror)
        }
      ).finally(
        ()=> closeDialog()
      )
    }
  }

  const navigateToHomescreen = ()=> {
    navigate('/home');
  }

  return(
    <PodComponentPage
      navigateToHomescreen = {navigateToHomescreen}
      devices = {devices}
      blinkPod = {blinkPod}
      openDialog = {openDialog}
      user = {user}
      loading = {loading}
      currentForm = {currentForm}
      selectedDevice = {selectedDevice}
      renameDevice = {renameDevice}
      statusText = {statusText}
      closeDialog = {closeDialog}
      addDevice = {addDevice}
      
      />
  )
}
export {PodsComponent}

// frontend/src/pods/pods.component.ts
import {Component, OnInit, OnDestroy} from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { DeviceService } from '../services/device.service';
import { AuthService } from '../services/auth.service';
import 'rxjs/add/operator/finally';

const BLINK_DELAY = 15000;

enum Forms {
  Remove = 1,
  Add,
  Rename
}

@Component({
  selector: 'app-pods',
  templateUrl: './pods.component.html',
  styleUrls: ['./pods.component.scss']
})
export class PodsComponent implements OnInit, OnDestroy {
  loading = false;
  devices: any[];
  currentForm: Forms;
  forms = Forms;
  selectedDevice: any;
  user: any;
  statusText = '  ';

  constructor(private route: ActivatedRoute,
              private router: Router,
              private deviceService: DeviceService,
              private authService: AuthService) { }

  ngOnInit() {
    this.user = this.authService.user;
    this.deviceService.getDevices(false, null, null, true).subscribe(devices => {
      this.devices = devices;
      for (const device of this.devices) {
        device['blinking'] = false;
      }
    });
  }

  ngOnDestroy() {
    const blinkingDevices = this.devices.filter(p => p.blinking === true);
    for (const device of blinkingDevices) {
      this.deviceService.blinkPod(device.id, 'stop').subscribe(() => { });
    }
  }

  blinkPod(device: any) {
    device.blinking = !device.blinking;
    if (device.blinking) {
      this.deviceService.blinkPod(device.id, 'start').subscribe(() => {
        device.timeout = setTimeout(() => {
          device.timeoutId = null;
          device.blinking = false;
        }, BLINK_DELAY);
      });
    } else {
      this.deviceService.blinkPod(device.id, 'stop').subscribe(() => {
        if (device.timeoutId !== null) {
          clearTimeout(device.timeoutId);
          device.timeoutId = null;
        }
      });
    }
  }

  openDialog(form: any, device: any) {
    this.currentForm = form;
    this.selectedDevice = device;
  }

  closeDialog() {
    this.currentForm = null;
    this.selectedDevice = null;
    this.statusText = '';
  }

  addDevice(macAddress) {
    macAddress = macAddress.trim();
    this.deviceService.addDevice(macAddress).finally(() => {
      this.closeDialog();
    }).subscribe(device => {
      this.devices.push(device);
    }, error => {
      alert('Failed to add pod: ' + error.json()['message']);
    });
  }

  removeDevice() {
    const device = this.selectedDevice;
    this.deviceService.removeDevice(device.id).finally(() => {
      this.closeDialog();
    }).subscribe(result => {
      this.devices = this.devices.filter(d => d !== device);
    }, error => {
      alert(error.json()['message']);
    });
  }

  renameDevice(newName) {
    if (this.selectedDevice.name === newName) {
      this.statusText = 'No change detected.';
    } else {
      const deviceId = this.selectedDevice.id;
      this.deviceService.setDevice(deviceId, {'name': newName}).finally(() => {
        this.closeDialog();
      }).subscribe(device => {
        const deviceIndex = this.devices.findIndex(s => s.id === device.id);
        if (deviceIndex > -1) {
          this.devices[deviceIndex].name = newName;
        }
      }, error => {
        alert(error.json()['message']);
      });
    }
  }

  navigateToHomescreen() {
    this.router.navigate(['homescreen']);
  }
}

<div class="container">
  <app-header title="Manage Pods" (backClick)="navigateToHomescreen()"></app-header>

  <div class="list-container">
    <ul class="list">
      <li *ngFor="let device of devices" class="pod-item">
        <svg x="0" y="0" width="20" height="18" viewBox="0 0 20 18" class="pod-icon pod-connected" [class.pod-disconnected]="!device.connected">
          <use xlink:href="../assets/img/icon-pod.svg#pod-icon"></use>
        </svg>
        <div class="pod-text">{{device.name}}</div>
        <div class="button-container">
          <button *ngIf="device.connected" class="pod-button" [class.selected-button]="device.blinking" (click)="blinkPod(device)">
            <svg x="0" y="0" width="20" height="20" viewBox="0 0 512 512" class="light-svg">
              <use xlink:href="../assets/img/light.svg#light-icon"></use>
            </svg>
          </button>
          <app-context-menu>
            <div class="menu-item" (click)="openDialog(forms.Rename, device)">Rename</div>
            <div *ngIf="user.isAdmin || user.isSuper" class="menu-item red" (click)="openDialog(forms.Remove, device)">Remove</div>
          </app-context-menu>
        </div>
      </li>
    </ul>
    <div [ngClass]="{ 'loading': loading }" class="load-text onload" *ngIf="devices === undefined">Loading...</div>
    <div class="empty-pod-list" *ngIf="devices !== undefined && devices.length == 0">
      <div class="load-text">There are no pods.</div>
      <div class="load-text-description">Add pods by clicking the button below.</div>
    </div>
  </div>
  <button *ngIf="user.isAdmin || user.isSuper" class="basic-button medium-button" (click)="openDialog(forms.Add)">Add via MAC address</button>
</div>

<app-dialog *ngIf="currentForm" (closeDialog)="closeDialog()">
  <div class="dialog-window">
    <ng-container *ngIf="currentForm == forms.Remove">
      <div class="dialog-heading">Remove Pod</div>
      <div class="dialog-body">Are you sure you want to remove this pod?</div>
      <button class="delete-button" (click)="removeDevice()">Remove</button>
      <button class="cancel-button" (click)="closeDialog()">Cancel</button>
    </ng-container>
    <ng-container *ngIf="currentForm == forms.Add">
      <div class="dialog-heading">Pod MAC address:</div>
      <input #macInput class="text-input" type="text" (keydown.enter)="addDevice(macInput.value)" >
      <div class="input-status-text">{{statusText}}</div>
      <button class="basic-button" (click)="addDevice(macInput.value)">Add</button>
      <button class="cancel-button" (click)="closeDialog()">Cancel</button>
    </ng-container>
    <ng-container *ngIf="currentForm == forms.Rename">
      <div class="dialog-heading">Pod Name:</div>
      <input #nameInput class="text-input" [value]="selectedDevice.name" type="text" (keydown.enter)="renameDevice(nameInput.value)" >
      <div class="input-status-text">{{statusText}}</div>
      <button class="basic-button" (click)="renameDevice(nameInput.value)">Rename</button>
      <button class="cancel-button" (click)="closeDialog()">Cancel</button>
    </ng-container>
  </div>
</app-dialog>
