// frontend/src/pods-overview/pods-overview-component.jsx
import { SessionService } from "../services/session-service";
import { SessionModel } from "../models/session";
import { DeviceService } from "../services/device-service";
import { DeviceModel } from "../models/device";
import { SpeakerModel } from "../models/speaker";
import { useState, useEffect } from "react";
import { useNavigate, useOutletContext } from "react-router-dom";
import { PodsOverviewPages } from "./html-pages";

function PodsOverviewComponent() {
  const [sessionClosing, setSessionClosing] = useState(false);
  const [openingDialog, setOpeningDialog] = useState(false);
  const [sessionDevices, setSessionDevices] = useState(null);
  const [session, setSession] = useState(null);
  const [sessionSpeaker, setSessionSpeakers] = useState([])
  const [selectedSessionDevice, setSelectedSessionDevice] = useState(null);
  //const [subscriptions, setSubscriptions] = useState([]);
  const [devices, setDevices] = useState([]);
  const [currentForm, setCurrentForm] = useState("");
  const [activeSessionService, setActiveSessionService] = useOutletContext();
  const navigate = useNavigate();
  const [trigger, setTrigger] = useState(0);
  const interval = 2000;

  useEffect(() => {
    if (activeSessionService !== null) {
      console.log("init session data");
      const nextSession = activeSessionService.getSession();
      setSession(nextSession);
      const nextSessionDevices = activeSessionService.getSessionDevices();
      setSessionDevices(nextSessionDevices);
      console.log("set Interval");

      getSessionSpeakers(nextSession.id)
      
      let intervalLoad = setInterval(() => {
        console.log("processing interval");
        const nextSession = activeSessionService.getSession();
        setSession(nextSession);
        const nextSessionDevices = [
          ...activeSessionService.getSessionDevices(),
        ];
        console.log(nextSessionDevices);
        setSessionDevices(nextSessionDevices);
      }, interval);

      // subscriptions.push(sessionSub, deviceSub);

      // return () => {
      //     subscriptions.map(sub => sub.unsubscribe());
      // }
      return () => {
        clearInterval(intervalLoad);
      };
    }
  }, [activeSessionService]);

  // so that the passcode renders in time
  useEffect(() => {
    console.log("reload");
  }, [trigger]);

  const goToDevice = (sessionDevice) => {
    navigate("/sessions/" + session.id + "/pods/" + sessionDevice.id);
  };

  const onSessionClosing = (isClosing) => {
    setSessionClosing(isClosing);
  };

  const navigateToSessions = () => {
    if (session.folder) {
      navigate("/sessions?folder=" + session.folder);
    } else {
      navigate("/sessions", { replace: true });
    }
  };

  const openDialog = (form) => {
    if (form === "AddDevice") {
      const fetchData = new DeviceService().getDevices(
        false,
        true,
        false,
        true
      );
      fetchData.then(
        (response) => {
          if (response.status === 200) {
            const resp2 = response.json();
            resp2.then((respdevices) => {
              const deviceresult = DeviceModel.fromJsonList(respdevices);
              setDevices(deviceresult);
              setCurrentForm(form);
            });
          }
        },
        (apierror) => {
          console.log("pods-overview-components func: openDialog 1 ", apierror);
        }
      );
    } else if (form === "Passcode" && session.end_date == null) {
      setCurrentForm(form);
    }
  };

  const getPasscode = () => {
    if (session !== null && session.end_date) {
      return "CLOSED";
    } else if (session !== null && session.passcode == null) {
      return "LOCKED";
    } else if (session !== null) {
      return session.passcode;
    } else {
      return "None";
    }
  };

  const addPodToSession = (deviceId) => {
    const fetchData = new SessionService().addPodToSession(
      this.session.id,
      deviceId
    );
    fetchData.then(
      (response) => {
        if (response.status === 200) {
          closeDialog();
        }
      },
      (apierror) => {
        console.log(
          "pods-overview-components func: addPodToSession 1 ",
          apierror
        );
      }
    );
  };

  const setPasscodeState = (state) => {
    const fetchData = new SessionService().setPasscodeStatus(session.id, state);
    fetchData.then(
      (response) => {
        if (response.status === 200) {
          closeDialog();
        }
        setSession(activeSessionService.getSession());
        setTrigger(trigger + 1);
      },
      (apierror) => {
        console.log(
          "pods-overview-components func: setPasscodeState 1 ",
          apierror
        );
      }
    );
  };

  // to make it easier on the user
  const copyPasscode = () => {
    let pwd = getPasscode();
    navigator.clipboard.writeText(pwd);
  };

  const exportSession = () => {
    const fetchData = new SessionService().downloadSessionReport(
      session.id,
      session.title
    );
    fetchData.then(
      (response) => {
        if (response.status === 200) {
          response.text().then((csvData) => {
            const anchor = document.createElement("a");
            anchor.href =
              "data:attachment/csv;charset=utf-8," + encodeURI(csvData);
            anchor.download = session.title + ".csv";
            anchor.click();
            console.log(csvData);
            console.log("Download successful.");
            //return true;
            /* {const resp = response.json()
                  resp.then() }*/
          });
        } else {
          alert("Failed to download session report.");
        }
      },
      (apierror) => {
        console.log(
          "pods-overview-components func: exportsession 1 ",
          apierror
        );
        alert("Failed to download session report.");
      }
    );
  };

  const closeDialog = () => {
    setCurrentForm("");
  };

  const goToGraph = () => {
    navigate("/sessions/" + session.id + "/graph");
  };

  const getRightEnabled = () => {
    if (session === null) {
      return false;
    } else if (session !== null) {
      if (session.recording === undefined) {
        return false;
      } else {
        return session.recording;
      }
    }
  };

  const getSessionSpeakers = (sessionID) => {
      const fetchData = new SessionService().getSessionSpeakers(sessionID);
      fetchData.then(
        (response) => {
          if (response.status === 200)
            response.json().then((jsonObj) => {
              const input = SpeakerModel.fromJsonList(jsonObj)
              const identified_speakers = []
              const uniqueSpeakers = []
              if(input && input.length){
                input.map((spkr, index)=>{
                  if(identified_speakers.indexOf(spkr.alias) == -1){
                    uniqueSpeakers.push(spkr)
                    identified_speakers.push(spkr.alias)
                  }
                })
                 setSessionSpeakers(uniqueSpeakers);
              }
            });
        },
        (apierror) => {
          console.log("pod-overview-component func getspeakers 1", apierror);
        }
      );
    };

    
  return (
    <PodsOverviewPages
      righttext={getPasscode()}
      rightenabled={getRightEnabled()}
      session={session}
      openDialog={openDialog}
      navigateToSessions={navigateToSessions}
      sessionDevices={sessionDevices}
      goToDevice={goToDevice}
      exportSession={exportSession}
      goToGraph={goToGraph}
      currentForm={currentForm}
      closeDialog={closeDialog}
      setPasscodeState={setPasscodeState}
      copyPasscode={copyPasscode}
      onSessionClosing={onSessionClosing}
      initialized={activeSessionService.initialized}
      sessionSpeaker={sessionSpeaker}
      devices={devices}
    />
  );
}

export { PodsOverviewComponent };

// client/src/app/pods-overview/pods-overview.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { SessionService } from '../services/session.service';
import { ActiveSessionService } from '../services/active-session.service';
import { DeviceService } from '../services/device.service';
import 'rxjs/add/operator/finally';

enum Forms {
    Passcode = 1,
    AddDevice
}

@Component({
    selector: 'app-pods-overview',
    templateUrl: './pods-overview.component.html',
    styleUrls: ['./pods-overview.component.scss']
})

export class PodsOverviewComponent implements OnInit, OnDestroy {
    sessionClosing = false;
    openingDialog = false;
    sessionDevices: any[] = [];
    session: any;
    selectedSessionDevice: any;
    subscriptions: any[] = [];
    devices: any[];
    currentForm: Forms = null;
    forms = Forms;

    POD_ON_COLOR = '#FF6655';
    POD_OFF_COLOR = '#D0D0D0';
    GLOW_COLOR = '#ffc3bd';

    constructor(private router: Router,
                private route: ActivatedRoute,
                private deviceService: DeviceService,
                private sessionService: SessionService,
                private activeSessionService: ActiveSessionService) { }

    ngOnInit() {
        const sessionSub = this.activeSessionService.getSession().subscribe(e => {
            this.session = e;
        });
        const deviceSub = this.activeSessionService.getSessionDevices().subscribe(e => {
            this.sessionDevices = e;
        });
        this.subscriptions.push(sessionSub, deviceSub);
    }

    ngOnDestroy() {
        this.subscriptions.map(sub => sub.unsubscribe());
    }

    goToDevice(sessionDevice) {
        this.router.navigate(['sessions', this.session.id, 'pods', sessionDevice.id]);
    }

    onSessionClosing(isClosing: boolean) {
        this.sessionClosing = isClosing;
    }

    navigateToSessions() {
        this.router.navigate(['sessions'], {queryParams: {folder: this.session.folder}});
    }

    openDialog(form: Forms) {
        if (form === this.forms.AddDevice) {
            this.deviceService.getDevices(false, true, false, true).subscribe(devices => {
                this.devices = devices;
                this.currentForm = form;
            });
        } else if (form === this.forms.Passcode && this.session.end_date == null) {
            this.currentForm = form;
        }
    }

    getPasscode() {
        if (this.session.end_date) {
            return 'CLOSED';
        } else if (this.session.passcode == null) {
            return 'LOCKED';
        } else {
            return this.session.passcode;
        }
    }

    addPodToSession(deviceId: number) {
        this.sessionService.addPodToSession(this.session.id, deviceId).subscribe(response => {
            this.closeDialog();
        });
    }

    setPasscodeState(state: string) {
        this.sessionService.setPasscodeStatus(this.session.id, state).subscribe(response => {
            this.closeDialog();
        });
    }

    exportSession() {
        this.sessionService.downloadSessionReport(this.session.id, this.session.title).subscribe(x => {
            console.log('Download successful.');
        }, error => {
            alert('Failed to download session report.');
        });
    }

    closeDialog() {
        this.currentForm = null;
    }

    goToGraph() {
        this.router.navigate(['sessions/' + this.session.id + '/graph']);
    }
}

<div class="container">
    <app-header [title]="'Overview'" (backClick)="navigateToSessions()" [rightText]="getPasscode()" (rightTextClick)="openDialog(forms.Passcode)" [rightEnabled]="session.recording"></app-header>
    <div class="list-container">
        <div class="load-text" *ngIf="sessionDevices === undefined">Loading...</div>
        <div class="load-text" *ngIf="sessionDevices !== undefined && sessionDevices.length == 0">No pods specified</div>
        <div *ngFor="let device of sessionDevices" (click)="goToDevice(device)" class="pod-overview-button">
            <svg class="pod-overview-icon" width="80px" height="80px" viewBox="-40 -40 80 80">
                <svg x="-8.5" y="-13.5" width="17" height="27" viewBox="0 0 17 27">
                    <use xlink:href="../assets/img/mic.svg#5" [attr.fill]="(device.connected) ? POD_ON_COLOR : POD_OFF_COLOR"></use>
                </svg>
                <svg:circle *ngIf="device.button_pressed" class="svgpulse" x="0" y="0" r="33.5" fill-opacity="0" [attr.stroke]="GLOW_COLOR"></svg:circle>
                <svg:circle x="0" y="0" r="30.5" fill-opacity="0" stroke-width="3" [attr.stroke]="(device.connected) ? POD_ON_COLOR : POD_OFF_COLOR"></svg:circle>
            </svg>
            <div>{{device.name}}</div>
        </div>
    </div>
    <div class="footer">
        <app-session-toolbar *ngIf='session' [session]="session" (closingSession)="onSessionClosing($event)">
            <span *ngIf="!session.end_date" class="toolbar-button" (click)="openDialog(forms.AddDevice)">
                <img class="button-icon" src="../../assets/img/icon-pod.svg">
                <div class="button-text">Add Pod</div>
            </span>
            <span class="toolbar-button" (click)="exportSession()">
                <img class="button-icon" src="../../assets/img/download.svg">
                <div class="button-text">Download</div>
            </span>
            <span class="toolbar-button" (click)="goToGraph()">
                    <img class="button-icon" src="../../assets/img/icon-graph.svg">
                    <div class="button-text">Graph</div>
                </span>
        </app-session-toolbar>
    </div>
</div>

<app-dialog *ngIf="currentForm" (closeDialog)="closeDeleteDialog()">
    <div *ngIf="currentForm == forms.AddDevice">
      <div class="dialog-heading">Add pod to Session</div>
      <ng-container *ngIf="devices.length > 0">
            <select #ddDevice class="dropdown-input">
                <option *ngFor="let device of devices" [value]="device.id">{{device.name}}</option>
            </select>
            <button class="basic-button" (click)="addPodToSession(ddDevice.value)">Add</button>
      </ng-container>
      <div *ngIf="devices.length == 0" class="unavailable-text">No devices available.</div>
      <button class="cancel-button" (click)="closeDialog()">Close</button>
    </div>
    <div *ngIf="currentForm == forms.Passcode">
        <div class="dialog-heading">Passcode Settings</div>
        <button class="basic-button" (click)="setPasscodeState('lock')">Lock</button>
        <button class="basic-button" (click)="setPasscodeState('unlock')">Unlock</button>
        <button class="basic-button" (click)="setPasscodeState('refresh')">Refresh</button>
        <button class="cancel-button" (click)="closeDialog()">Cancel</button>
    </div>
</app-dialog>
