// client/src/app/transcripts/transcripts.component.ts
import { Component, OnInit, OnDestroy, ViewChildren, ElementRef, QueryList } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ActiveSessionService } from '../services/active-session.service';
import { similarityToRGB } from '../globals';

enum Forms {
  Keyword = 1,
  Options
}

@Component({
  selector: 'app-transcripts',
  templateUrl: './transcripts.component.html',
  styleUrls: ['./transcripts.component.scss']
})
export class TranscriptsComponent implements OnInit, OnDestroy {

  @ViewChildren('transcriptElement') set transcriptElements(elements: QueryList<ElementRef>) {
    if (elements && !this.hasScrolled) {
      const match = elements.find(el => el.nativeElement.id === this.transcriptIndex);
      if (match) {
        match.nativeElement.scrollIntoView();
        this.hasScrolled = true;
      }
    }
  }

  sessionDeviceId: number;
  session: any;
  sessionDevice: any;
  transcripts: any;
  transcriptIndex: string;
  dialogKeywords: any;
  forms = Forms;
  currentForm: Forms = null;
  displayTranscripts: any[];
  subscriptions: any[] = [];
  hasScrolled = false;
  showKeywords = true;
  showDoA = false;

  constructor(private router: Router,
              private route: ActivatedRoute,
              private activeSessionService: ActiveSessionService) {  }

  ngOnInit() {
    this.route.queryParams.subscribe(params => {
      this.transcriptIndex = params['index'];
    });
    this.route.params.subscribe(params => {
      this.sessionDeviceId = +params['sessionDeviceId'];
      this.activeSessionService.getSession().subscribe( e => {
        this.session = e;
      });
      const deviceSub = this.activeSessionService.getSessionDevice(this.sessionDeviceId).subscribe( e => {
        this.sessionDevice = e;
      });
      const transcriptSub = this.activeSessionService.getSessionDeviceTranscripts(this.sessionDeviceId).subscribe( e => {
        this.transcripts = e;
        this.createDisplayTranscripts();
      });
      this.subscriptions.push(deviceSub, transcriptSub);
    });
  }

  ngOnDestroy() {
    this.subscriptions.map(sub => sub.unsubscribe());
  }

  createDisplayTranscripts() {
    this.displayTranscripts = [];
    for (const transcript of this.transcripts) {
      const result = [];
      const words = transcript.transcript.split(' ');
      for (const word of words) {
        const matchingKeywords = [];
        let highestSimilarity = 0;
        if (this.showKeywords) {
          for (const keyword of transcript.keywords) {
            if (word.toLowerCase().startsWith(keyword.word.toLowerCase())
                && !matchingKeywords.find(item => item.keyword === keyword.keyword)) {
              if (keyword.similarity > highestSimilarity) {
                highestSimilarity = keyword.similarity;
              }
              matchingKeywords.push(keyword);
            }
          }
        }
        result.push({
          'word': word,
          'matchingKeywords': (matchingKeywords.length > 0) ? matchingKeywords : null,
          'color': similarityToRGB(highestSimilarity)
        });
      }
      transcript['words'] = result;
      transcript['doaColor'] = (this.showDoA) ? this.angleToColor(transcript.direction) : this.angleToColor(-1);
      this.displayTranscripts.push(transcript);
    }
  }

  angleToColor(angle: number) {
    if (angle === -1) {
      return 'hsl(0, 100%, 100%)';
    } else {
      return 'hsl(' + angle + ', 100%, 95%)';
    }
  }

  openKeywordDialog(dialogKeywords) {
    this.dialogKeywords = dialogKeywords;
    this.currentForm = this.forms.Keyword;
  }

  openOptionsDialog() {
    this.currentForm = this.forms.Options;
  }

  closeDialog() {
    this.currentForm = null;
  }

  formatSeconds(s) {
    const date = new Date(1000 * Math.floor(s));
    return date.toISOString().substr(11, 8);
  }

  navigateToSession() {
    this.router.navigate(['/sessions/' + this.session.id + '/pods/' + this.sessionDeviceId]);
  }
}

<div class="container">
  <app-header [title]="' Transcripts from ' + sessionDevice.name" (backClick)="navigateToSession()" [rightText]="'Options'" (rightTextClick)="openOptionsDialog()"></app-header>
  <div class="transcript-list">
    <div *ngFor="let transcript of displayTranscripts; let last = last;">
      <div id="{{transcript.id}}" #transcriptElement class="transcript-container" [class.highlighted]="transcript.id == transcriptIndex" [style.background-color]="transcript.doaColor">
        <div class="timestamp">{{formatSeconds(transcript.start_time)}}</div>
        <div class="transcript-text">
          <span *ngIf="transcript.speaker_tag" class="bold">{{transcript.speaker_tag}}: </span>
          <span *ngFor="let transcriptData of transcript.words">
            <span *ngIf="transcriptData.matchingKeywords !== null" [style.color]="transcriptData.color" (click)="openKeywordDialog(transcriptData.matchingKeywords)" class="highlight-keyword"> {{transcriptData.word}}</span>
            <span *ngIf="transcriptData.matchingKeywords === null">{{transcriptData.word}}</span>
          </span>
        </div>
      </div>
      <hr *ngIf="!last">
    </div>
  </div>
</div>
<app-dialog *ngIf="currentForm" (closeDialog)="closeKeywordDialog()">
  <div *ngIf="currentForm == forms.Keyword" class="dialog-box">
    <div class="dialog-heading">Keyword Data</div>
    <div class="dialog-body"><span class="bold">Word:</span> {{dialogKeywords[0].word}} </div>
    <div class="dialog-body"><span class="bold">Keywords (Similarity):</span></div>
    <div class="dialog-body">
      <span *ngFor="let keyword of dialogKeywords; let last = last">
        {{keyword.keyword}} ({{keyword.similarity}}%){{last ? '' : ','}}
      </span>
    </div>
    <button class="delete-button" (click)="closeDialog()">Close</button>
  </div>
  <div *ngIf="currentForm == forms.Options"  class="dialog-box">
    <div class="dialog-heading">Transcript Options</div>
    <br>
    <label class="dc-checkbox">Show keywords
      <input type="checkbox" checked="checked" [(ngModel)]="showKeywords" (ngModelChange)="createDisplayTranscripts()">
      <span class="checkmark"></span>
    </label>
    <label class="dc-checkbox">Show direction of arrival
      <input type="checkbox" checked="checked" [(ngModel)]="showDoA" (ngModelChange)="createDisplayTranscripts()">
      <span class="checkmark"></span>
    </label>
    <br>
    <button class="delete-button" (click)="closeDialog()">Close</button>
  </div>
</app-dialog>

// frontend/src/transcripts/transcripts-component.jsx
import { useEffect, useState } from 'react';
import { formatHMS as formatSeconds } from "../globals";
import { useNavigate, useOutletContext,useParams, useSearchParams } from 'react-router-dom';
import { similarityToRGB } from '../globals';
import {TranscriptComponentPage} from './html-pages'
import { useD3 } from '../myhooks/custom-hooks';
import * as d3 from 'd3';

function TranscriptsComponent(){

  // @ViewChildren('transcriptElement') set transcriptElements(elements: QueryList<ElementRef>) {
  //   if (elements && !this.hasScrolled) {
  //     const match = elements.find(el => el.nativeElement.id === this.transcriptIndex);
  //     if (match) {
  //       match.nativeElement.scrollIntoView();
  //       this.hasScrolled = true;
  //     }
  //   }
  // }

  
  const [sessionDevice, setSessionDevice] = useState({});
  const [session, setSession] = useState({});
  const [transcripts, setTranscripts] = useState([]);
  const [transcriptIndex, setTranscriptIndex] = useState("");
  const [dialogKeywords, setDialogKeywords] = useState();
  const [currentForm, setCurrentForm] = useState("");
  const [displayTranscripts, setDisplayTranscripts] = useState([]);
  const [subscriptions, setSubscriptions] = useState([]);
  const [hasScrolled, setHasScrolled] = useState(false);
  const [showKeywords, setShowKeywords] = useState(true);
  const [trigger, setTrigger] = useState(0)
  const [showDoA,setShowDoA] = useState(false);
  const [reload, setReload] = useState(false)
  const [activeSessionService, setActiveSessionService] = useOutletContext();
  const { sessionDeviceId } = useParams(); 
  const [searchParam, setSearchParam] = useSearchParams();
  const navigate = useNavigate()
  
  const colorTopicDict = ['hsl(0, 100%, 100%)', 'hsl(151, 58%, 87%)', 'hsl(109, 67%, 92%)', 'hsl(49, 94%, 93%)', 'hsl(34, 100%, 89%)', 'hsl(30, 79%, 85%)'];
  
  useEffect(()=>{
    const index = searchParam.get('index');
    if(index !== undefined){
      setTranscriptIndex(parseInt(index, 10))
    }

    if(sessionDeviceId !== undefined){
      const sessSub = activeSessionService.getSession();
      if(sessSub !== undefined) {
        setSession(sessSub);
      }

      const deviceSub = activeSessionService.getSessionDevice(sessionDeviceId)
      if(deviceSub !== undefined){
        setSessionDevice(deviceSub);
      }

      if (transcripts.length <= 0) {
        const transcriptSub = activeSessionService.getTranscripts()
         //const transcriptSub = activeSessionService.getSessionDeviceTranscripts(sessionDeviceId, setTransripts);

         transcriptSub.subscribe(e => {
             if (Object.keys(e).length !== 0) {
                 const data = e.filter(t => t.session_device_id === parseInt(sessionDeviceId, 10))
                     .sort((a, b) => (a.start_time > b.start_time) ? 1 : -1)
                 setTranscripts(data)
                 setReload(true)
             }
         })
         subscriptions.push(transcriptSub);
     }
    }
      
    

    return () => {
      subscriptions.map(sub => {
          if (sub.closed) {
              sub.unsubscribe()
          }
      });
  }
},[])

useEffect(()=>{
  if(reload){
    createDisplayTranscripts();
  }
},[reload])

useEffect(()=>{
  if(trigger > 0){
    createDisplayTranscripts();
  }
},[trigger])

const createDisplayTranscripts = ()=> {
    const accdisplaytrans = [];
    for (const transcript of transcripts) {
      const result = [];
      const words = transcript.transcript.split(' ');
      for (const word of words) {
        const matchingKeywords = [];
        let highestSimilarity = 0;
        if (showKeywords) {
          for (const keyword of transcript.keywords) {
            if (word.toLowerCase().startsWith(keyword.word.toLowerCase())
                && !matchingKeywords.find(item => item.keyword === keyword.keyword)) {
              if (keyword.similarity > highestSimilarity) {
                highestSimilarity = keyword.similarity;
              }
              matchingKeywords.push(keyword);
            }
          }
        }
        result.push({
          'word': word,
          'matchingKeywords': (matchingKeywords.length > 0) ? matchingKeywords : null,
          'color': similarityToRGB(highestSimilarity)
        });
      }
      transcript['words'] = result;
      transcript['doaColor'] = showDoA ? angleToColor(transcript.direction, transcript.topic_id) : angleToColor(-1, transcript.topic_id);
      accdisplaytrans.push(transcript);
    }
    setDisplayTranscripts(accdisplaytrans)
  }

  const angleToColor = (angle, id)=> {
    if (angle === -1) {
      return colorTopicDict[id + 1];
    } else {
      return 'hsl(' + angle + ', 100%, 95%)';
    }
  }

  const openKeywordDialog = (dialogKeywords) =>{
    setDialogKeywords(dialogKeywords);
    setCurrentForm("Keyword");
  }

  const openOptionsDialog = ()=> {
    setCurrentForm("Options");
  }

  const closeDialog = ()=> {
    setCurrentForm("");
  }


  const navigateToSession = ()=> {
    navigate('/sessions/' + session.id + '/pods/' + sessionDeviceId);
  }
  
  const toggleKeywords = ()=> {
    setShowKeywords(!showKeywords);
    setTrigger(trigger + 1)
  }
  
  const legendRef = useD3(
       (svg) => {
         const data = ["No topic", "1", "2", "3", "4", "5"];
         // Create a color scale
         const colorScale = d3.scaleOrdinal()
           .domain(data)
           .range(colorTopicDict.map((c) => d3.hsl(c)));

         // Create legend
         const legend = svg
          .selectAll(".legend")
          .data(data)
          .enter()
          .append("g")
          .attr("class", "legend")
          .attr("transform", (d, i) => `translate(0, ${i * 20})`);
       
        // Add colored rectangles to the legend
        legend
          .append("rect")
          .attr("width", 18)
          .attr("height", 18)
          .style("fill", (d) => colorScale(d));

        // Add text labels to the legend
        legend
          .append("text")
          .attr("x", 24)
          .attr("y", 9)
          .attr("dy", ".35em")
          .style("text-anchor", "start")
          .text((d) => d);
        }
  )  

  return(
    <TranscriptComponentPage
      sessionDevice = {sessionDevice}
      currentForm = {currentForm}
      navigateToSession = {navigateToSession}
      displayTranscripts = { displayTranscripts}
      formatSeconds = {formatSeconds}
      openKeywordDialog = {openKeywordDialog}
      closeDialog = {closeDialog}
      dialogKeywords = {dialogKeywords}
      showDoA = {showDoA}
      transcriptIndex = {transcriptIndex}
      createDisplayTranscripts = {createDisplayTranscripts}
      openOptionsDialog = {openOptionsDialog}
      legendRef = {legendRef}
      showKeywords = {showKeywords}
      toggleKeywords = {toggleKeywords}
    />
  )
}

export {TranscriptsComponent}
