// frontend/src/timeline/timeline-component.jsx
import style from './timeline.module.css'
import { formatSeconds } from '../globals';
import { useEffect, useState } from 'react';
import { adjDim } from '../myhooks/custom-hooks';


function AppTimeline(props) {
    const TIMELINE_LEFT = 16;
    const TIMELINE_WIDTH = 341;
    const MIN_UTTERANCE_WIDTH = 1;
    const [_transcripts, setTranscripts] = useState(props.transcripts)
    const [displayTranscripts, setDisplayTranscripts] = useState([]);
    const [previousTranscriptCount, setPreviousTranscriptCount] = useState(0);
    const [startText, setStartText] = useState('Start');
    const [endText, setEndText] = useState('Now');
    const [_start, setStart] = useState();
    const [_end, setEnd] = useState();
    //const [reload, setReload] = useState(false);

    useEffect(() => {
    	
        if (props.transcripts !== undefined) {
            setTranscripts(props.transcripts);
            refreshTimeline();
        }

        if (props.start !== undefined) {
            setStart(props.start);
            if (props.start === 0) {
                setStartText('Start');
            } else {
                setStartText(formatSeconds(_start));
            }
            refreshTimeline();
        }

        if (props.end !== undefined) {
            setEnd(props.end);
            if (props.end === props.session.length) {
                setEndText((props.session.recording) ? 'Now' : 'End');
            } else {
                setEndText(formatSeconds(_end));
            }
            refreshTimeline();
        }
        //setReload(true)
    }, [props.transcripts])


    const refreshTimeline = () => {
        const duration = _end - _start;
        const temptranscript = [] 
        if(props.transcripts !== undefined){
        for (const transcript of props.transcripts) {
            const pct_start = (transcript.start_time - _start) / duration;
            const pct_length = transcript.length / duration;
            const displayTranscript = {};
            displayTranscript['transcript'] = transcript;
            displayTranscript['left'] = adjDim(pct_start * TIMELINE_WIDTH + TIMELINE_LEFT);
            displayTranscript['width'] = adjDim(Math.min(Math.max(pct_length * TIMELINE_WIDTH,
                MIN_UTTERANCE_WIDTH), TIMELINE_WIDTH * (1 - pct_start)));
                temptranscript.push(displayTranscript);
        }
    }
        setDisplayTranscripts(temptranscript);
    }

    const openTranscriptDialog = (transcript) => {
        props.clickedTimeline(transcript);
    }
   

    return (
        <div className="small-section">
            <div className={style.legend}>
                <span className={`${style["color-box"]} ${style.question}`}></span>
                <span className={style["legend-text"]}>Question</span>
                <span className={`${style["color-box"]} ${style.discussion}`}></span>
                <span className={style["legend-text"]}>Discussion</span>
                <span className={`${style["color-box"]} ${style.silence}`}></span>
                <span className={style["legend-text"]}>Silence</span>
            </div>
            <div className={style.line}></div>
            <div className={style.timeline}>
                {
                    displayTranscripts.map((transcript, index) => (
                        <span key={index}>
                            <span
                                className={transcript.transcript.question ? `${style["utterance"]} ${style["question"]}` : style["utterance"]}
                                onClick={() => openTranscriptDialog(transcript.transcript)}
                                style={{ left: `${transcript.left}` + 'px', width: `${transcript.width}` + 'px' }}>
                            </span>
                        </span>
                    ))
                }

            </div>
            <div className={style["time-textbox"]}>
                <div className={style["time-text"]}>{startText}</div>
                <div className={style["time-text"]}>{endText}</div>
            </div>
        </div>
    )
}

export {AppTimeline}

// client/src/app/timeline/timeline.component.ts
import { Component, Input, Output, EventEmitter, DoCheck, OnInit, OnDestroy } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { SessionModel } from '../models/session';
import { TranscriptModel } from '../models/transcript';
import { formatSeconds } from '../globals';

const TIMELINE_LEFT = 16;
const TIMELINE_WIDTH = 341;
const MIN_UTTERANCE_WIDTH = 1;

@Component({
  selector: 'app-timeline',
  templateUrl: './timeline.component.html',
  styleUrls: ['./timeline.component.scss']
})
export class TimelineComponent {
    @Input('session') session: SessionModel;
    @Input('transcripts')
    set setTranscripts(value: any) {
        this._transcripts = value;
        this.refreshTimeline();
    }
    @Input('start')
    set setStart(value: any) {
        this._start = value;
        if (this._start === 0) {
            this.startText = 'Start';
        } else {
            this.startText = formatSeconds(this._start);
        }
        this.refreshTimeline();
    }
    @Input('end')
    set setEnd(value: any) {
        this._end = value;
        if (this._end === this.session.length) {
            this.endText = (this.session.recording) ? 'Now' : 'End';
        } else {
            this.endText = formatSeconds(this._end);
        }
        this.refreshTimeline();
    }
    @Output() clickedTimeline = new EventEmitter<Object>();

    _transcripts: TranscriptModel[] = [];
    displayTranscripts = [];
    previousTranscriptCount = 0;
    startText = 'Start';
    endText = 'Now';
    _start: number;
    _end: number;

    constructor() { }

    refreshTimeline() {
        const duration = this._end - this._start;
        this.displayTranscripts = [];
        for (const transcript of this._transcripts) {
            const pct_start = (transcript.start_time - this._start) / duration;
            const pct_length = transcript.length / duration;
            const displayTranscript = {};
            displayTranscript['transcript'] = transcript;
            displayTranscript['left'] = pct_start * TIMELINE_WIDTH + TIMELINE_LEFT;
            displayTranscript['width'] = Math.min(Math.max(pct_length * TIMELINE_WIDTH,
                MIN_UTTERANCE_WIDTH), TIMELINE_WIDTH * (1 - pct_start));
            this.displayTranscripts.push(displayTranscript);
        }
    }

    openTranscriptDialog(transcript: any) {
        this.clickedTimeline.emit(transcript);
    }
}

<div class="timeline-container">
    <div class="legend">
        <span class="color-box question"></span>
        <span class="legend-text">Question</span>
        <span class="color-box discussion"></span>
        <span class="legend-text">Discussion</span>
        <span class="color-box silence"></span>
        <span class="legend-text">Silence</span>
    </div>
    <div class="line"></div>
    <div class="timeline">
        <span *ngFor="let transcript of displayTranscripts">
            <span class="utterance" (click)="openTranscriptDialog(transcript.transcript)" [class.question]="transcript.transcript.question" [style.left.px]="transcript.left" [style.width.px]="transcript.width"></span>
        </span>
    </div>
    <div class="time-textbox">
        <div class="time-text">{{startText}}</div>
        <div class="time-text">{{endText}}</div>
    </div>
</div>
