// client/src/app/features/features.component.ts
import { Component, Input } from '@angular/core';
import { SessionModel } from '../models/session';
import { TranscriptModel } from '../models/transcript';

@Component({
  selector: 'app-features',
  templateUrl: './features.component.html',
  styleUrls: ['./features.component.scss']
})
export class FeaturesComponent {
  @Input('session') session: SessionModel;
  @Input('transcripts')
  set setTranscripts(value: any) {
    this._transcripts = value;
    this.updateGraphs();
  }
  private _transcripts: TranscriptModel[] = [];
  private svgWidth = 74;
  private svgHeight = 39;
  features: any[] = [];
  featureDescription = null;
  featureHeader = null;
  showFeatureDialog = false;

  constructor() { }

  updateGraphs() {
    // Create feature array.
    const valueArrays = [{ 'name': 'Emotional tone', 'values': [] },
                        { 'name': 'Analytic thinking', 'values': [] },
                        { 'name': 'Clout', 'values': [] },
                        { 'name': 'Authenticity', 'values': [] },
                        { 'name': 'Confusion', 'values': [] }];
    this._transcripts.map(t => {
      valueArrays[0].values.push(t.emotional_tone_value);
      valueArrays[1].values.push(t.analytic_thinking_value);
      valueArrays[2].values.push(t.clout_value);
      valueArrays[3].values.push(t.authenticity_value);
      valueArrays[4].values.push(t.certainty_value);
    });
    for (const valueArray of valueArrays) {
      const length = valueArray.values.length;
      const average = valueArray.values.reduce((sum, current) => sum + current, 0) / ((length > 0) ? length : 1);
      const last = (length > 0) ? valueArray.values[length - 1] : 0;
      const trend = (last > average) ? 1 : (last === average) ? 0 : -1;
      let path = '';
      for (let i = 0; i < length; i++) {
        const xPos = Math.round(((i + 1) / length) * this.svgWidth);
        const yPos = this.svgHeight - Math.round((valueArray.values[i] / 100) * this.svgHeight);
        path += (i === 0) ? 'M' : 'L';
        path += `${xPos} ${yPos} `;
      }
      valueArray['average'] = average;
      valueArray['last'] = last;
      valueArray['trend'] = trend;
      valueArray['path'] = path;
    }
    this.features = valueArrays;
  }

  getInfo(featureName) {
    switch (featureName) {
      case 'Emotional tone': {
        this.featureDescription = 'Scores above 50 indicate a positive emotional tone. Scores below 50 indicate a negative emotional tone.';
      }
      break;
      case 'Analytic thinking': {
        this.featureDescription = 'Scores above 50 indicate analytic thinking. Scores below 50 indicate narrative thinking.';
      }
      break;
      case 'Clout': {
        this.featureDescription = 'Scores above 50 indicate higher levels of confidence or leadership.';
      }
      break;
      case 'Authenticity': {
        this.featureDescription = 'Scores above 50 indicate higher levels of honesty or authentic communication.';
      }
      break;
      case 'Confusion': {
        this.featureDescription = 'Scores above 50 indicate higher levels of confusion in a speaker’s communication.';
      }
      break;
    }
    this.featureHeader = featureName;
    this.showFeatureDialog = true;
  }

  closeDialog() {
    this.showFeatureDialog = false;
  }
}


<div>
  <table class="features-table">
    <thead>
      <tr>
        <th class="desc-header">Classifier</th>
        <th class="score-header">Score</th>
        <th class="graph-header">Graph</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let feature of features">
        <td>
         <img (click)="getInfo(feature.name)" class="info-button" src="../../assets/img/question.svg"/>
          {{ feature.name }}
        </td>
        <td class="score">
          <div class="number">{{ feature.average | number : '1.0-0' }}</div>
          <div class="direction-indicator" [class.positive]="feature.trend == 1" [class.neutral]="feature.trend == 0"
          [class.negative]="feature.trend == -1"> </div>
        </td>
        <td>
          <span *ngIf="feature.values.length == 0" class="no-data-span" [style.width.px]="74"></span>
          <svg viewBox="0 -0.5 74 39.5" class="svg">
            <path [attr.d]="feature.path" fill="none" [class.positive]="feature.trend >= 0" [class.negative]="feature.trend == -1"></path>
          </svg>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<app-dialog *ngIf="showFeatureDialog">
  <div class=add-dialog>
    <div class="dialog-heading">{{ featureHeader }}</div>
    {{featureDescription}}
   <button class="cancel-button" (click)="closeDialog()">Close</button>
  </div>
</app-dialog>

// frontend/src/components/individualmetrics/features-component.jsx
import { useEffect, useState } from "react";
import { IndividualFeaturePage } from "./html-pages-individual";

function AppIndividualFeaturesComponent(props) {
  // @Input('session') session: SessionModel;

  // @Input('transcripts')
  // set setTranscripts(value: any) {
  //   this._transcripts = value;
  //   this.updateGraphs();
  // }
  const svgWidth = 74;
  const svgHeight = 39;
  //const [_transcripts, setTranscript] = useState([]);
  const [features, setFeatures] = useState([]);
  const [featureDescription, setFeatureDescription] = useState(null);
  const [featureHeader, setFeatureHeader] = useState(null);
  const [showFeatureDialog, setShowFeatureDialog] = useState(false);

  useEffect(() => {
    updateGraphs();
  });

  //update new metrics (individual)
  const updateGraphs = () => {
    const valueArrays = [
      { name: "Participation", values: [],'time':[] },
      { name: "Social Impact", values: [],'time':[] },
      { name: "Responsivity", values: [],'time':[] },
      { name: "Internal Cohesion", values: [],'time':[] },
      { name: "Newness", values: [],'time':[] },
      { name: "Communication Density", values: [],'time':[] },
      
    ];
    if(!props.transcripts || !props.transcripts.length || props.spkrId === -1)
    {
      setFeatures(valueArrays);
      return;
    }
    props.transcripts.forEach((t) => {
      //select speaker metrics from transcripts based on the spkrId
      const speaker_metric = t.speaker_metrics.find(
        (item) => item.speaker_id === props.spkrId
      );

      //accumulate each score into their value array
      valueArrays[0].values.push(speaker_metric.participation_score * 100);
      valueArrays[1].values.push(speaker_metric.social_impact * 100);
      valueArrays[2].values.push(speaker_metric.responsivity * 100);
      valueArrays[3].values.push(speaker_metric.internal_cohesion * 100);
      valueArrays[4].values.push(speaker_metric.newness * 100);
      valueArrays[5].values.push(speaker_metric.communication_density * 100);

      valueArrays[0].time.push(t.start_time);
      valueArrays[1].time.push(t.start_time);
      valueArrays[2].time.push(t.start_time);
      valueArrays[3].time.push(t.start_time);
      valueArrays[4].time.push(t.start_time);
    });

    console.log("transcript data: ", valueArrays)
    
    //smooth the values of the value array over 10 values
    for (const valueArray of valueArrays) {
      const length = valueArray.values.length;
      const average =
        valueArray.values.reduce((sum, current) => sum + current, 0) /
        (length > 0 ? length : 1);
      const last = length > 0 ? valueArray.values[length - 1] : 0;
      const trend = last > average ? 1 : last === average ? 0 : -1;
      let path = "";
      const smoothedValues = [];

      // Calculate the average of each 10 x units
      for (let i = 0; i < length; i += 10) {
        const chunk = valueArray.values.slice(i, i + 10);
        const chunkAverage =
          chunk.reduce((sum, current) => sum + current, 0) / chunk.length;
        smoothedValues.push(chunkAverage);
      }

      // Generate the SVG path using the smoothed values
      for (let i = 0; i < smoothedValues.length; i++) {
        const xPos = Math.round(((i + 1) / smoothedValues.length) * svgWidth);
        const yPos =
          svgHeight - Math.round((smoothedValues[i] / 100) * svgHeight);
        path += i === 0 ? "M" : "L";
        path += `${xPos} ${yPos} `;
      }

      valueArray["average"] = average;
      valueArray["last"] = last;
      valueArray["trend"] = trend;
      valueArray["path"] = path;
    }
    setFeatures(valueArrays);
  };

  const getInfo = (featureName) => {
    switch (featureName) {
      case "Participation":
        {
          setFeatureDescription("How much you participate above or below the average.");
          break;
        }
      case "Social mpact":
        {
          setFeatureDescription("How much your speech is related to the following response.");
          break;
        }
      case "Responsivity":
        {
          setFeatureDescription("How much your response is related to the other's speech.");
          break;
        }
      case "Internal Cohesion":
        {
          setFeatureDescription("How much your speech is realted to itself.");
          break;
        }
      case "Newness":
        {
          setFeatureDescription("How much new info you present throughout the discussion");
          break;
        }
      case "Communication Density":
        {
          setFeatureDescription("The amount of word per speech segment");
          break;
        }
      default:
        console.log("no text");
    }
    setFeatureHeader(featureName);
    setShowFeatureDialog(true);
  };

  const closeDialog = () => {
    setShowFeatureDialog(false);
  };

  return (
    <IndividualFeaturePage
      featureHeader={featureHeader}
      featureDescription={featureDescription}
      closeDialog={closeDialog}
      showFeatureDialog={showFeatureDialog}
      features={features}
      getInfo={getInfo}
      showFeatures={props.showFeatures}
    />
  );
}

export { AppIndividualFeaturesComponent };
