// frontend/src/components/folder-select/folder-select.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-folder-select',
  templateUrl: './folder-select.component.html',
  styleUrls: ['./folder-select.component.scss']
})
export class FolderSelectComponent implements OnInit {
  @Input('folders')
  set folders(value: any[]) {
    if (value != null) {
      this._folders = value;
      this.displayFolder();
    }
  }
  @Output() itemSelected = new EventEmitter<any>();

  get folder(): number {
    return this.selectedFolder;
  }

  get breadcrumb(): string {
    const crumbnames = this.breadcrumbs.map(b => b.name);
    if (this.selectedFolder !== -1) {
      const currentFolder = this._folders.find(f => f.id === this.selectedFolder);
      crumbnames.push(currentFolder.name);
    }
    crumbnames.unshift('Home');
    return crumbnames.join('/');
  }

  _folders: any[];
  visibleFolders: any[] = [];
  selectedFolder: any;
  breadcrumbs: any [] = [];
  recentFolder: any;

  constructor(private route: ActivatedRoute) {}

  ngOnInit() {
    this.route.queryParams.subscribe(params => {
      this.recentFolder = this._folders.find(f => f.id === (parseInt(params['folder'], 10)));
      if (this.recentFolder) {
        this.displayFolder(this.recentFolder.parent);
      }
    });
  }

  displayFolder(folderId?) {
    if (!folderId || folderId === undefined) {
      this.visibleFolders = this._folders.filter(f => f.parent == null);
      this.breadcrumbs = [];
    } else {
      this.visibleFolders = this._folders.filter(x => x.parent === folderId);
      this.breadcrumbs = [];
      let folder = this._folders.find(f => f.id === folderId);
      this.breadcrumbs.unshift(folder);
      while (folder.parent) {
        folder = this._folders.find(f => f.id === folder.parent);
        this.breadcrumbs.unshift(folder);
      }
    }
  }

  hasChildren(folder) {
    const children = this._folders.filter(x => x.parent === folder.id);
    return children.length > 0;
  }

  setSelectedFolder(id) {
    this.selectedFolder = id;
  }
}

<div class="list-container">
  <div *ngIf="visibleFolders.length == 0"> There is no valid location for this item. </div>
  <ng-container *ngIf="visibleFolders.length > 0">
    <div class="breadcrumb-container">
      <img *ngIf="breadcrumbs.length == 1" src="../assets/img/icon-back.svg" class="breadcrumb-arrow-icon" (click)="displayFolder()">
      <img *ngIf="breadcrumbs.length > 1" src="../assets/img/icon-back.svg" class="breadcrumb-arrow-icon" (click)="displayFolder(breadcrumbs[breadcrumbs.length - 2].id)">
      <span (click)="displayFolder()" class="crumb-name"> Home</span>
      <span *ngIf="breadcrumbs.length > 1" class="breadcrumbs"> / . . . / </span>
      <span *ngIf="breadcrumbs.length == 1" class="breadcrumbs"> / </span>
      <div *ngIf="breadcrumbs.length > 0" class="crumb-name">{{ breadcrumbs[breadcrumbs.length - 1].name}}</div>
    </div>
    <ul class="list">
      <li *ngFor="let folder of visibleFolders" class="folder-item" (click)="setSelectedFolder(folder.id)" [class.selected]="folder.id == selectedFolder">
        <img src="../assets/img/folder.svg" class="folder-icon">
        <div class="folder-title">{{folder.name}}</div>
        <img *ngIf="hasChildren(folder)" src="../assets/img/icon-forward.svg" class="open-folder-icon" (click)="displayFolder(folder.id)">
      </li>
      <li *ngIf="visibleFolders[0].parent == null" class="folder-item" (click)="setSelectedFolder(-1)" [class.selected]="-1 == selectedFolder">
        <img src="../assets/img/home.svg" class="add-to-home">
        <div class="folder-title"> Home </div>
      </li>
    </ul>
  </ng-container>
</div>

// frontend/src/components/folder-select/folder-select-component.jsx
import { useEffect, useState } from "react";
import { useSearchParams } from 'react-router-dom';
import {AppFolderPage} from './html-pages'

function AppFolderSelectComponent(props){
  const [_folders, setFolders] = useState(props.selectableFolders);
  const [visibleFolders, setVisibleFolders] = useState([]);
  const [selectedFolder, setSelectFolder] = useState(null);
  const [breadcrumbs, setBreadCrumbs] = useState([]);
  const [recentFolder, setRecentFolder] = useState(null) ;
  const [searchParam, setSearchParam] = useSearchParams();


  useEffect(()=>{
    if(Object.keys(props.selectableFolders).length !== 0){
      displayFolder()
    } 
  },[])

  useEffect(()=> {
    const folder = searchParam.get('folder');
    const reFolder = _folders.find(f => f.id === (parseInt(folder, 10)))
    setRecentFolder(reFolder);
      if (reFolder) {
        displayFolder(reFolder.parent);
      }
  },[])

  // @Output() itemSelected = new EventEmitter<any>();



  const getbreadcrumb = (folderid)=>{
    const crumbnames = breadcrumbs.map(b => b.name);
    if (folderid !== -1) {
      const currentFolder = _folders.find(f => f.id === folderid);
      crumbnames.push(currentFolder.name);
    }
    crumbnames.unshift('Home');
    return crumbnames.join('/');
  }

  
  const displayFolder = (folderId) =>{
    if (!folderId || folderId === undefined) {
      setVisibleFolders(_folders.filter(f => f.parent == null));
      setBreadCrumbs([]);
    } else {
      setVisibleFolders(_folders.filter(x => x.parent === folderId));
      const bread = [] 
      let folder = _folders.find(f => f.id === folderId);
      bread.unshift(folder);
      if(folder){
      while (folder.parent) {
        folder = _folders.find(f => f.id === folder.parent);
        bread.unshift(folder);
      }
    }
    setBreadCrumbs(bread);
    }
  }

  const hasChildren = (folder)=> {
    const children = _folders.filter(x => x.parent === folder.id);
    return children.length > 0;
  }

  const setSelectedFolderEvent = (id) =>{
    props.setFolderSelect(id)
    if(props.setBreadCrumbSelect){
      const bread = getbreadcrumb(id)
      props.setBreadCrumbSelect(bread)
      //setBreadCrumbs(bread)
    }
    setSelectFolder(id);
  }

  return(
    <AppFolderPage
      visibleFolders = {visibleFolders}
      breadcrumbs = {breadcrumbs}
      displayFolder = {displayFolder}
      setSelectedFolderEvent = {setSelectedFolderEvent}
      selectedFolder = {selectedFolder}
      hasChildren = {hasChildren}
    />
  )
}

export {AppFolderSelectComponent}
