// frontend/src/create-session/create-session-component.jsx
import { DeviceService } from '../services/device-service';
import { SessionService } from '../services/session-service';
import { KeywordService } from '../services/keyword-service';
import { TopicModelService } from "../services/topic-model-service";
import { formatDate } from '../globals';
import { DeviceModel } from '../models/device'
import { KeywordListModel } from '../models/keyword-list'
import { SessionModel } from '../models/session'
import { FolderModel } from '../models/folder';
import { TopicModelModel } from '../models/topic-model';
import { unpackTopModels } from '../myhooks/custom-hooks';
import { useEffect, useState } from 'react';
import {CreateSessionPage} from './html-pages'
import { useNavigate, useSearchParams, useLocation } from 'react-router-dom';


function CreateSessionComponent(props) {
  const BLINK_DELAY = 15000;
  //Previous state
  const location = useLocation();
  const prevState = location.state;
  const changedState = prevState != null;
  // Page Data
  const [user, setUser] = useState(null);
  const [devices, setDevices] = useState([]);
  const [keywordLists, setKeywordLists] = useState([]);
  const [topicModels, setTopicModels] = useState([]);

  //menus = Menus;
  const [currentMenu, setCurrentMenu] = useState(changedState ? prevState.currentMenu : 'Settings');
  const [pageTitle, setPageTitle] = useState(changedState ? prevState.pageTitle : 'New session');
  //forms = Forms;
  const [currentForm, setCurrentForm] = useState("");
  const [displayText, setDisplayText] = useState('');

  // Session Data
  const [sessionName, setSessionName] = useState(changedState ? prevState.sessionName : '');
  const [byod, setByod] = useState(changedState ? prevState.byod : true);
  const [doa, setDoa] = useState(changedState ? prevState.doa : true);
  const [features, setFeatures] = useState(changedState ? prevState.features : true);
  const [selectedKeywordList, setSelectedKeywordList] = useState(changedState ? prevState.selectedKeywordList : null);
  const [selectedTopicModel, setSelectedTopicModel] = useState(changedState ? prevState.selectedTopicModel : null);
  const [selectedDevices, setSelectedDevices] = useState([]);
  const [folder, setFolder] = useState(changedState ? prevState.folder : -1);
  const [folderPath, setFolderPath] = useState(changedState ? prevState.folderPath : 'Home');
  const [folders, setFolders] = useState([]);
  const [folderSelect, setFolderSelect] = useState(null)
  const [breadCrumbSelect, setBreadCrumbSelect] = useState(null)
  const navigate = useNavigate();
  const [searchParam, setSearchParam] = useSearchParams()
  
  

  useEffect(() => {
    setUser(props.userdata);
    const fetchData = new DeviceService().getDevices(false, true, false, true)
    fetchData.then(
      response => {
        if (response == 200) {
          const resp2 = response.json()
          resp2.then(
            respdevices => {
              const deviceresult = DeviceModel.fromJsonList(respdevices)
              setDevices(deviceresult);
              setSelectedDevices([]);
              for (const device of deviceresult) {
                // Add custom view fields to pods.
                device['selected'] = false;
                device['blinking'] = false;
              }
            }
          )
        }
      },
      apierror => {
        console.log("create-session-components func: useEffect 1 ", apierror)
      }
    )

    const fetchData2 = new KeywordService().getKeywordLists();
    fetchData2.then(
      response => {
        if (response.status === 200) {
          const resp2 = response.json()
          resp2.then(
            respkeyword => {
              
              const keywordLists = KeywordListModel.fromJsonList(respkeyword)
              setKeywordLists(keywordLists);
              for (const keywordList of keywordLists) {
                keywordList['keywordsText'] = keywordList.keywords.join(', ');
              }
            }
          )
        }
      },
      apierror => {
        console.log("create-session-components func: useEffect 2 ", apierror)
      }
    )

    const fetchData3 = new SessionService().getFolders()
    fetchData3.then(
      response => {
        if (response.status == 200) {
          const resp = response.json()
          resp.then(
            folderss => {
              const folderresult = FolderModel.fromJsonList(folderss)
              setFolders(folderresult);
              const paramfolder = searchParam.get('folder');
              const passedFolderId = +parseInt(paramfolder, 10);
              if (folder > 0) {
              } else if (passedFolderId > -1) {
                setFolderLocation(passedFolderId, buildBreadcrumbs(passedFolderId));
              } else {
                setFolderLocation(passedFolderId, folderPath);
              }

            })
        }
      },
      apierror => {
        console.log("create-session-components func: useEffect 3 ", apierror)
      }
    )
    
    const fetchData4 = new TopicModelService().getTopicModels();
    fetchData4.then(
      (response) => {
        if (response.status === 200) {
          const resp = response.json()
          resp.then(
            (result) => {
              const topModels = TopicModelModel.fromJsonList(result);
              setTopicModels(unpackTopModels(topModels));
            },
            (err) => { console.log('CreateSessionComponent error func : useeffect 122' ,err) })

        } else {
          console.log('CreateSessionComponent error func : useeffect 1', response)
        }
      },
      (apierror) => {
        console.log('CreateSessionComponent error func : useeffect 2', apierror)
      }
    )

    if (!changedState) {
      goToSettings();
    }

    return () => {
      const blinkingDevices = devices.filter(p => p.blinking === true);
      for (const device of blinkingDevices) {
        new DeviceService().blinkPod(device.id, 'stop');//.subscribe(() => { });
      }
    }
  }, [])



  const setFolderLocation = (folderId, pathString)=>{
    setFolder(folderId);
    setFolderPath(pathString);
    closeDialog();
  }
  
  const receiveEmmitedFolder = (e) =>{
    if (e === -1) {
      setFolder(null);
    } else {
      setFolder(e);
    }
    setCurrentForm("");
  }

  const buildBreadcrumbs = (folderId)=> {
    const breadcrumbs = [];
    let folderB = folders.find(f => f.id === folderId);
    if (folderB != null) {
      breadcrumbs.unshift(folderB);
      while (folderB.parent) {
        folderB = folders.find(f => f.id === folderB.parent);
        breadcrumbs.unshift(folderB);
      }
    }
    if (breadcrumbs.length > 0) {
      const crumbnames = breadcrumbs.map(b => b.name);
      crumbnames.unshift('Home');
      return crumbnames.join('/');
    }
  }

  const createSession = ()=> {
    if (!sessionName && sessionName.trim() === '') {
      openDialog("Error", 'Invalid Session Name');
      setCurrentMenu("Settings");
    } else {
      const deviceIds = selectedDevices.map(d => d.id);
      const keywordListId = (selectedKeywordList) ? selectedKeywordList.id : null;
      const topicModelId = (selectedTopicModel) ? selectedTopicModel.id : null;
      const fetchData = new SessionService().createNewSession(sessionName, deviceIds, keywordListId, topicModelId, byod, features, doa, folder)
      fetchData.then(
        response=>{
          if(response.status === 200){
            const resp = response.json();
            resp.then(
              result =>{
                const s = SessionModel.fromJson(result)
                navigate("/sessions/" + s.id);
                //  this.router.navigate(['sessions', s.id, 'overview']);
              }
            )
          }else{
            openDialog("Error", response.json()['message']);
            goToSettings();
          }
        },
        apierror=>{
          console.log("create-session-components func: createSession 1 ", apierror)
        }
      )  
    }
  }

  // ---------------------
  // Keyword Menu
  // ---------------------

  const formatKeywordDate = (date)=> {
    return formatDate(date);
  }

  // ---------------------
  // Device Menu
  // ---------------------

  const deviceSelected = (device)=> {
    if (!selectedDevices.includes(device)) {
      selectedDevices.push(device);
    } else {
      setSelectedDevices(selectedDevices.filter(d => d !== device));
    }
  }

  const onClickSelectAll = ()=> {
    if (selectedDevices.length === devices.length) {
      setSelectedDevices([]);
    } else {
      setSelectedDevices(devices);
    }
  }

  const blinkPod = (e, device)=> {
    e.stopPropagation();
    device.blinking = !device.blinking;
    if (device.blinking) {
      const fetchData = new DeviceService().blinkPod(device.id, 'start')
      fetchData.then(
        response => {
          if(response.status === 200){
            device.timeout = setTimeout(() => {
              device.timeoutId = null;
              device.blinking = false;
            }, BLINK_DELAY);
          }
        },
        apierror =>{
          console.log("create-session-components func: blinkPad 1 ", apierror)
        }
      )
    } else {
      const fetchData2 = new DeviceService().blinkPod(device.id, 'stop')
      fetchData2.then(
        response => {
          if(response.status === 200){
            if (device.timeoutId !== null) {
              clearTimeout(device.timeoutId);
              device.timeoutId = null;
            }
          }
        },
        apierror => {
          console.log("create-session-components func: blinkPad 2 ", apierror)
        }
      )
    }
  }

  // ---------------------
  // Navigation and Dialog
  // ---------------------

  const goToKeywords = ()=> {
    setCurrentMenu("Keywords");
    setPageTitle('New session');
  }
  
  const goToTopModels = ()=> {
    setCurrentMenu("TopModels");
    setPageTitle('New session');
  }

  const goToSettings = ()=> {
    setCurrentMenu("Settings");
    setPageTitle('New session');
  }

  const goToDevices = () =>{
    setCurrentMenu("Devices");
    setPageTitle('New session');
  }

  const navigateToSessions = ()=> {
    navigate('/sessions');
  }
  
  const navigateToKeywordLists = () =>{
    navigate('/keyword-lists/new-session', getStateInfo());
  }
  
  const navigateToFileUpload = () => {
    navigate('/file_upload/new-session', getStateInfo());
  }
  
  const getStateInfo = () => {
    return {state: {sessionName: sessionName, byod: byod, features: features, doa: doa, folder: folder, folderPath: folderPath, currentMenu: currentMenu, pageTitle: pageTitle, selectedKeywordList: selectedKeywordList, selectedTopicModel: selectedTopicModel}};
  }

  const openDialog = (form, text)=> {
    setCurrentForm(form);
    setDisplayText(text);
  }

  const closeDialog = ()=> {
    setCurrentForm("");
  }

  return(
    <CreateSessionPage 
    pageTitle = {pageTitle}
    navigateToSessions = {navigateToSessions}
    currentMenu = {currentMenu}
    sessionName = {sessionName}
    setSessionName = {setSessionName}
    folderPath = {folderPath}
    setByod = {setByod}
    byod = {byod}
    doa = {doa}
    setDoa = {setDoa}
    features = {features}
    setFeatures = {setFeatures}
    goToKeywords = {goToKeywords}
    keywordLists = {keywordLists}
    selectedKeywordList = {selectedKeywordList}
    setSelectedKeywordList = {setSelectedKeywordList}
    topicModels = {topicModels}
    selectedTopicModel = {selectedTopicModel}
    setSelectedTopicModel = {setSelectedTopicModel}
    formatKeywordDate = {formatKeywordDate}
    navigateToKeywordLists = {navigateToKeywordLists}
    navigateToFileUpload = {navigateToFileUpload}
    goToSettings = {goToSettings}
    goToDevices = {goToDevices}
    devices = {devices}
    deviceSelected = {deviceSelected}
    selectedDevices = {selectedDevices}
    blinkPod = {blinkPod}
    onClickSelectAll = {onClickSelectAll}
    createSession = {createSession}
    closeDialog = {closeDialog}
    setFolderLocation = {setFolderLocation}
    displayText = {displayText}
    folders = {folders}
    currentForm = {currentForm}
    openDialog = {openDialog}
    folderSelect = {folderSelect}
    setFolderSelect = {setFolderSelect}
    breadCrumbSelect = {breadCrumbSelect}
    setBreadCrumbSelect = {setBreadCrumbSelect}
    goToTopModels = {goToTopModels}
    />
  )
}

export {CreateSessionComponent}

// client/src/app/create-session/create-session.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { DeviceService } from '../services/device.service';
import { AuthService } from '../services/auth.service';
import { SessionService } from '../services/session.service';
import { KeywordService } from '../services/keyword.service';
import { Router, ActivatedRoute } from '@angular/router';
import { formatDate } from '../globals';
import { FolderModel } from '../models/folder';

enum Menus {
  Settings = 1,
  Keywords,
  Devices
}

enum Forms {
  Error = 1,
  Folder = 2
}

const BLINK_DELAY = 15000;

@Component({
  selector: 'app-create-session',
  templateUrl: './create-session.component.html',
  styleUrls: ['./create-session.component.scss']
})
export class CreateSessionComponent implements OnInit, OnDestroy {

  // Page Data
  user: any;
  devices: any[] = [];
  keywordLists: any[] = [];

  menus = Menus;
  currentMenu: Menus = Menus.Settings;
  pageTitle = 'Create Session';
  forms = Forms;
  currentForm: Forms = null;
  displayText = '';

  // Session Data
  sessionName = '';
  byod = true;
  doa = true;
  features = true;
  selectedKeywordList: any = null;
  selectedDevices: any[] = [];
  folder = -1;
  folderPath = 'Home';
  folders: any[];

  constructor(private deviceService: DeviceService,
              private sessionService: SessionService,
              private router: Router,
              private authService: AuthService,
              private route: ActivatedRoute,
              private keywordService: KeywordService) { }

  ngOnInit() {
    this.user = this.authService.user;
    this.deviceService.getDevices(false, true, false, true).subscribe( devices => {
      this.devices = devices;
      this.selectedDevices = [];
      for (const device of devices) {
        // Add custom view fields to pods.
        device['selected'] = false;
        device['blinking'] = false;
      }
    });

    this.keywordService.getKeywordLists().subscribe(keywordLists => {
      this.keywordLists = keywordLists;
      for (const keywordList of this.keywordLists) {
        keywordList['keywordsText'] = keywordList.keywords.join(', ');
      }
    });
    this.sessionService.getFolders().subscribe(folders => {
      this.folders = folders;
      this.route.queryParams.subscribe(params => {
        const passedFolderId = +params['folder'];
        if (passedFolderId > -1) {
          this.setFolderLocation(passedFolderId, this.buildBreadcrumbs(passedFolderId));
        } else {
          this.setFolderLocation(passedFolderId, this.folderPath);
        }
      });
    });
    this.goToSettings();
  }

  ngOnDestroy() {
    const blinkingDevices = this.devices.filter(p => p.blinking === true);
    for (const device of blinkingDevices) {
      this.deviceService.blinkPod(device.id, 'stop').subscribe(() => { });
    }
  }

  setFolderLocation(folderId, pathString) {
    this.folder = folderId;
    this.folderPath = pathString;
    this.closeDialog();
  }
  receiveEmmitedFolder(e: any) {
    if (e === -1) {
      this.folder = null;
    } else {
    this.folder = e;
    }
    this.currentForm = null;
  }

  buildBreadcrumbs(folderId) {
    const breadcrumbs = [];
    let folder = this.folders.find(f => f.id === folderId);
    if (folder != null) {
      breadcrumbs.unshift(folder);
      while (folder.parent) {
        folder = this.folders.find(f => f.id === folder.parent);
        breadcrumbs.unshift(folder);
      }
    }
    if (breadcrumbs.length > 0) {
      const crumbnames = breadcrumbs.map(b => b.name);
      crumbnames.unshift('Home');
       return crumbnames.join('/');
      }
    }

  createSession() {
    if (!this.sessionName && this.sessionName.trim() === '') {
      this.openDialog(this.forms.Error, 'Invalid Session Name');
      this.currentMenu = this.menus.Settings;
    } else {
      const deviceIds = this.selectedDevices.map(d => d.id);
      const keywordListId = (this.selectedKeywordList) ? this.selectedKeywordList.id : null;
      this.sessionService.createNewSession(this.sessionName, deviceIds, keywordListId,
        this.byod, this.features, this.doa, this.folder).subscribe(s => {
        this.router.navigate(['sessions', s.id, 'overview']);
      }, error => {
        this.openDialog(this.forms.Error, error.json()['message']);
        this.goToSettings();
      });
    }
  }

  // ---------------------
  // Keyword Menu
  // ---------------------

  formatKeywordDate(date) {
    return formatDate(date);
  }

  // ---------------------
  // Device Menu
  // ---------------------

  deviceSelected(device: any) {
    if (!this.selectedDevices.includes(device)) {
      this.selectedDevices.push(device);
    } else {
      this.selectedDevices = this.selectedDevices.filter(d => d !== device);
    }
  }

  onClickSelectAll() {
    if (this.selectedDevices.length === this.devices.length) {
      this.selectedDevices = [];
    } else {
      this.selectedDevices = this.devices;
    }
  }

  blinkPod(e: any, device: any) {
    e.stopPropagation();
    device.blinking = !device.blinking;
    if (device.blinking) {
      this.deviceService.blinkPod(device.id, 'start').subscribe(() => {
        device.timeout = setTimeout(() => {
          device.timeoutId = null;
          device.blinking = false;
        }, BLINK_DELAY);
      });
    } else {
      this.deviceService.blinkPod(device.id, 'stop').subscribe(() => {
        if (device.timeoutId !== null) {
          clearTimeout(device.timeoutId);
          device.timeoutId = null;
        }
      });
    }
  }

  // ---------------------
  // Navigation and Dialog
  // ---------------------

  goToKeywords() {
    this.currentMenu = this.menus.Keywords;
    this.pageTitle = 'Create Discussion: Keywords';
  }

  goToSettings() {
    this.currentMenu = this.menus.Settings;
    this.pageTitle = 'Create Discussion: Settings';
  }

  goToDevices() {
    this.currentMenu = this.menus.Devices;
    this.pageTitle = 'Create Discussion: Devices';
  }

  navigateToSessions() {
    this.router.navigate(['/sessions']);
  }

  navigateToKeywordLists() {
    this.router.navigate(['/keyword-lists/new']);
  }

  openDialog(form: Forms, text: string) {
    this.currentForm = form;
    this.displayText = text;
  }

  closeDialog() {
    this.currentForm = null;
  }
}

<div class="container">
  <app-header [title]="pageTitle" (backClick)="navigateToSessions()"></app-header>

  <ng-container *ngIf="currentMenu == menus.Settings">
    <div class="list-container">
      <span>Discussion name:</span>
      <input #txtName [(ngModel)]="sessionName" class="text-input" maxlength=64>
      <div>Folder: </div>
      <span class="path-container">
        <input type="text" class="folder-input" name="Location" [placeholder]="folderPath" readonly>
        <img src="../assets/img/open-folder.svg" id="open-folder-icon" (click)=openDialog(forms.Folder,test)>
      </span>
      <label class="dc-checkbox">Allow participant devices
        <input type="checkbox" checked="checked" [(ngModel)]="byod">
        <span class="checkmark"></span>
      </label>
      <label class="dc-checkbox">Capture discussion direction
        <input type="checkbox" checked="checked" [(ngModel)]="doa">
        <span class="checkmark"></span>
      </label>
      <label class="dc-checkbox">Analyze discussion features
        <input type="checkbox" checked="checked" [(ngModel)]="features">
        <span class="checkmark"></span>
      </label>
    </div>
    <button class="footer-button" (click)="navigateToSessions()">Back</button>
    <button class="footer-button" (click)="goToKeywords()">Next</button>
  </ng-container>

  <ng-container *ngIf="currentMenu == menus.Keywords">
    <div class="list-container">
      <div class="empty-keyword-list" *ngIf="keywordLists && keywordLists.length == 0">
        <div class="load-text"> No Keyword Lists </div>
        <div class="load-text-description"> Tap the button below to make your first keyword list. </div>
      </div>
      <div *ngFor="let keywordList of keywordLists" class="keyword-list-button" [class.keywords-selected]="selectedKeywordList == keywordList" (click)="selectedKeywordList = keywordList">
        <div class="keyword-list-header">
          <span class="title">{{keywordList.name}}</span>
          <span class="date"> - {{formatKeywordDate(keywordList.creation_date)}}</span>
        </div>
        <div class="keyword-list-keywords">{{keywordList.keywordsText}}</div>
      </div>
    </div>
    <button class="footer-button" (click)="navigateToKeywordLists()">Create Keyword List</button>
    <button class="footer-button" (click)="goToSettings()">Back</button>
    <button class="footer-button" (click)="goToDevices()">Next</button>
  </ng-container>

  <ng-container *ngIf="currentMenu == menus.Devices">
    <div class="list-container">
      <div *ngIf="devices.length == 0" class="empty-keyword-list">
        <div class="load-text"> No Devices </div>
      </div>
      <ul *ngIf="devices.length > 0" class="list">
        <li *ngFor="let device of devices" class="pod-item" (click)="deviceSelected(device);" [class.selected-pod]="selectedDevices.includes(device)">
          <img class="pod-icon" src="../../assets/img/icon-pod.svg">
          <div class="pod-text">{{device.name}}</div>
          <div class="button-container">
            <button class="pod-button" [class.selected-button]="device.blinking" (click)="blinkPod($event, device)">
              <svg x="0" y="0" width="20" height="20" viewBox="0 0 512 512" class="light-svg">
                <use xlink:href="../assets/img/light.svg#light-icon"></use>
              </svg>
            </button>
          </div>
        </li>
      </ul>
    </div>
    <button class="select-all" (click)="onClickSelectAll()">Select All</button>
    <button class="footer-button" (click)="goToKeywords()">Back</button>
    <button class="footer-button" (click)="createSession()">Start Discussion</button>
  </ng-container>
</div>

<app-dialog *ngIf="currentForm" (closeDialog)="closeDeleteDialog()">
  <div *ngIf="currentForm == forms.Error" class="add-dialog">
    <div class="dialog-heading">Invalid Sesion</div>
    {{ displayText }}
    <button class="cancel-button" (click)="closeDialog()">Close</button>
  </div>

  <div *ngIf="currentForm == forms.Folder" class="dialog-window">
    <div class=dialog-heading> Select Folder</div>
    <app-folder-select #folderSelect [folders]="folders" (itemSelected)="receiveEmmitedFolder($event)"></app-folder-select>
    <button *ngIf="folderSelect.folder" class="dialog-button" (click)="setFolderLocation(folderSelect.folder, folderSelect.breadcrumb)">OK</button>
    <button class="cancel-button" (click)="closeDialog()">Cancel</button>
  </div>
</app-dialog>
