// frontend/src/session-toolbar/session-toolbar-component.jsx
import { SessionService } from '../services/session-service';
import { useEffect, useState } from 'react';
import { useNavigate, useLocation, useSearchParams } from 'react-router-dom'
import { AppSessionPage } from './html-pages'

function AppSessionToolbar(props) {
    // @Input('session') session: SessionModel;
    // @Output() closingSession = new EventEmitter<boolean>();
    
    const [timeText, setTimeText] = useState('');
    const [sessionEnding, setSessionEnding] = useState();
    const [intervalId, setInterValid] = useState();
    const [searchParam, setSearchParam] = useSearchParams();
    const navigate = useNavigate();
    const location = useLocation()



    useEffect(() => {
        console.log(props.session.length,'session length')
        const intvalId = setInterval(() => {
            updateTime();
        }, 1000);
        setInterValid(intvalId)
        updateTime();
        //destroy function
        return () => {
            clearInterval(intvalId);
        }
    }, [props.session])


    const updateTime = () => {
        //console.log(props.session.length,'session length')
        // doesn't currently support displaying hours
        const m = Math.floor(props.session.length / 60);
        const s = Math.floor(props.session.length - m * 60);
        let secs_text;
        if (s < 10) {
            secs_text = '0' + s;
        } else {
            secs_text = '' + s;
        }
        setTimeText(m + ':' + secs_text);
    }

    const onEndSession = () => {
        // do smth diff for just deleting one thing, I think I have it tho
        let deleteDevice = location.pathname == '/join';
        setSessionEnding(true);
        props.closingSession(true);
        const fetchData = deleteDevice ? (new SessionService().removeDeviceFromSession(props.session.id, props.sessionDevice.id, true)) : (new SessionService().endSession(props.session.id));
        fetchData.then(response => {
            if (response.status === 200) {
                setSessionEnding(false);
                if (deleteDevice) {
                    navigate('/join')
                } else {
                    if (props.session.folder) {
                    	 // works now, just had to switch the lines
                    	 setSearchParam({ folder: props.session.folder })
                        navigate('/sessions?folder=' + props.session.folder);
                    } else {
                        navigate('/sessions', { replace: true })
                    }
                }
            }
        })
    }

    return (
        < AppSessionPage
            sessionEnding={sessionEnding}
            timeText={timeText}
            innerhtml={props.children}
            session={props.session}
            onEndSession={onEndSession}
            menus={props.menus}
        />
    )
}

export { AppSessionToolbar }

// client/src/app/session-toolbar/session-toolbar.component.ts
import { Component, Input, Output, OnInit, OnDestroy, EventEmitter} from '@angular/core';
import { Router } from '@angular/router';
import { SessionService } from '../services/session.service';
import { SessionModel } from '../models/session';

@Component({
  selector: 'app-session-toolbar',
  templateUrl: './session-toolbar.component.html',
  styleUrls: ['./session-toolbar.component.scss']
})
export class SessionToolbarComponent implements OnInit, OnDestroy {
    @Input('session') session: SessionModel;
    @Output() closingSession = new EventEmitter<boolean>();
    timeText: string;
    sessionEnding = false;
    intervalId: any;

    constructor(private router: Router,
                private sessionService: SessionService ) { }

    ngOnInit() {
        this.intervalId = setInterval(() => {
            this.updateTime();
            if (!this.session.recording) {
                clearInterval(this.intervalId);
            }
        }, 1000);
        this.updateTime();
    }

    ngOnDestroy() {
        clearInterval(this.intervalId);
    }

    updateTime() {
        // doesn't currently support displaying hours
        const m = Math.floor(this.session.length / 60);
        const s = Math.floor(this.session.length - m * 60);
        let secs_text: string;
        if (s < 10) {
          secs_text = '0' + s;
        } else {
          secs_text = '' + s;
        }
        this.timeText = m + ':' + secs_text;
    }

    onEndSession() {
        this.sessionEnding = true;
        this.closingSession.emit(true);
        this.sessionService.endSession(this.session.id).subscribe(e => {
            this.router.navigate(['sessions'], {queryParams: {folder: this.session.folder}});
            this.sessionEnding = false;
        });
    }

    closeEndDialog() {
        this.sessionEnding = false;
    }
}

<div class="footer-bar" [class.dialog-blur]="sessionEnding">
    <div class="session-toolbar">
        <span class="session-time">
            <div class="time">{{timeText}}</div>
            <div class="info">Total duration</div>
        </span>
        <span class="middle-content">
            <ng-content></ng-content>
        </span>
        <span *ngIf="session.recording" class="session-end" (click)="onEndSession()">
            <button class="end-button">End</button>
        </span>
    </div>
</div>

<app-dialog *ngIf="sessionEnding" (closeDialog)="closeEndDialog()">
    <div class="dialog-content">
        <div class="dialog-heading">Session Ending...</div>
        <div class="dialog-spinner"><app-spinner></app-spinner></div>
    </div>
</app-dialog>
