// client/src/app/login/login.component.ts
import { Component, OnInit, HostListener, ViewChild, ElementRef } from '@angular/core';
import { AuthService } from '../services/auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  @ViewChild('username') txtUsername: ElementRef;
  @ViewChild('password') txtPassword: ElementRef;

  loginErrorText = null;
  showLoginDialog = false;

  constructor(private router: Router,
              private authService: AuthService) { }

  ngOnInit() {
    this.authService.me().subscribe(response => {
      this.router.navigate(['homescreen']);
    }, error => {});
  }

  login() {
    if (this.txtUsername.nativeElement.value.trim() === '') {
      this.loginErrorText = 'Please enter your username or email.';
      this.txtUsername.nativeElement.focus();
      this.showLoginDialog = true;
    } else if (this.txtPassword.nativeElement.value.trim() === '') {
      this.loginErrorText = 'Please enter your password.';
      this.txtPassword.nativeElement.focus();
      this.showLoginDialog = true;
    } else {
      this.authService.login(this.txtUsername.nativeElement.value, this.txtPassword.nativeElement.value).subscribe(e => {
        this.router.navigate(['homescreen']);
      },
      error => {
        if (error.status === 429) {
          this.loginErrorText = 'You are attempting to login too frequently.  Please try again later.';
        } else {
          this.loginErrorText = error.json()['message'];
        }
        this.showLoginDialog = true;
      });
    }
  }

  @HostListener('document:keyup.enter', ['$event'])
  onKeydownHandler(event: KeyboardEvent) {
    if (event.keyCode === 13 && this.showLoginDialog) {
      this.closeDialog();
    } else if (event.keyCode === 13) {
      this.login();
    }
  }

  closeDialog() {
    this.showLoginDialog = false;
  }

  navigateBack() {
    this.router.navigate(['']);
  }
}


<div class="container">
  <app-header [title]="'Sign In'" (backClick)="navigateBack()"></app-header>
  <br>
  <div class="instruction">Please enter your username and password.</div>
  <input class="text-input" #username placeholder="username / email" name="username">
  <input class="text-input" #password placeholder="password" type="password" name="password">
  <button class="basic-button medium-button" (click)='login()'>Sign In</button>

  <app-dialog *ngIf="showLoginDialog">
   <div class="add-dialog">
      <div class="dialog-heading">Login Failed</div>
     {{ loginErrorText }}
     <button class="cancel-button" (click)="closeDialog()">Close</button>
   </div>
  </app-dialog>
</div>

// frontend/src/login/login-component.jsx
import { useNavigate } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { Instruction } from '../utilities/utility-components';
import { Appheader } from '../header/header-component';
import { DialogBox } from '../dialog/dialog-component';
import { AuthService } from '../services/auth-service';


function LoginPage() {
  const navigate = useNavigate();
  const [isShow, setShow] = useState(false);
  const [message, setMessage] = useState('');
  const [loginStatus, setLoginStatus] = useState(0)
  const [authObject, setAuthObject] = useState(null)

  useEffect(() => {
    if (loginStatus.status === 200 && authObject !== null) {
      const dest = authObject.role === 'study' ? '/app' : '/home';
      return navigate(dest) //,{state: authObject}
    } else if (loginStatus.status === 400) {
      setMessage(loginStatus.message);
      setShow(true);
    } else if (loginStatus.status === 401) {
      return navigate('/login')
    } else if (loginStatus.status === 600) {
      setMessage("Inavlid Username or Password");
      setShow(true);
    }
  }, [loginStatus,authObject])

  
  const dialogheader = 'Login Failed';

  const backClick = () => {
    return navigate('/')
  }

  const closeDialogBox = () => {
    setShow(false);
  }

  const checkLogin = () => {
    const username = document.getElementById("username").value.trim();
    const password = document.getElementById("password").value.trim();
    if (username === '') {
      setMessage("Please Enter Your Username");
      setShow(true);
      document.getElementById("username").focus();
    } else if (password === '') {
      setMessage("Please Enter Your Password");
      setShow(true);
      document.getElementById("password").focus();
    } else {
      new AuthService().login(username, password, setLoginStatus,setAuthObject);
    }

  }

  return (
    <div className="main-container items-center text-center">

      <Appheader
        title="Sign In"
        leftText={false}
        rightText={""}
        rightEnabled={false}
        nav={backClick} />
      <br></br>
      <Instruction instructions="Please enter your username and password." />

      <input className="text-box my-2 small-section" placeholder="username / email" name="username" id='username' />
      <input className="text-box small-section" placeholder="password" type="password" name="password" id='password' />

      <button className="wide-button"  onClick={checkLogin}>
        Sign In
      </button>

      <DialogBox
        itsclass={"add-dialog"}
        heading={dialogheader}
        message={message}
        show={isShow}
        closedialog={closeDialogBox} />
    </div >
  )
}

export { LoginPage }
