// frontend/src/sessions/sessions-component.jsx
import { useState, useEffect } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { SessionService } from "../services/session-service";
import { SessionModel } from "../models/session";
import { FolderModel } from "../models/folder";
import { DiscussionSessionPage } from "./html-pages";

function SessionsComponent(props) {
  //forms = Forms;
  const [currentForm, setCurrentForm] = useState("");
  const [sessions, setSessions] = useState([]);
  const [folders, setFolders] = useState([]);
  const [displayedFolders, setDisplayedFolders] = useState([]);
  const [displayedSessions, setDisplayedSessions] = useState([]);
  const [selectableFolders, setSelectableFolders] = useState([]);
  const [selectedSession, setSelectedSession] = useState(null);
  const [selectedFolder, setSelectedFolder] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [showAlert, setShowAlert] = useState(false);
  const [alertMessage, setAlertMessage] = useState("");
  const [breadcrumbs, setBreadCrumbs] = useState([]);
  const [currentFolder, setCurrentFolder] = useState("");
  const [folderPath, setFolderPath] = useState("");
  const [folderSelect, setFolderSelect] = useState(null);
  const [invalidName, setInvalidName] = useState(false);
  const navigate = useNavigate();
  const [searchParam, setSearchParam] = useSearchParams();

  useEffect(() => {
    const fetchData = new SessionService().getSessions();
    fetchData.then(
      (response) => {
        if (response.status === 200) {
          const resp = response.json();
          resp.then(
            (session) => {
              const sessresult = SessionModel.fromJsonList(session);
              setSessions(sessresult);
              const fetchData2 = new SessionService().getFolders();
              fetchData2.then(
                (response) => {
                  if (response.status === 200) {
                    const resp2 = response.json();
                    resp2.then((folders) => {
                      const folderresult = FolderModel.fromJsonList(folders);
                      setFolders(folderresult);
                      setIsLoading(false);
                    });
                  }
                },
                (apierror2) => {
                  console.log(
                    "sessions-components func: useEffect 4 ",
                    apierror2
                  );
                }
              );
            },
            (error) => {
              console.log("sessions-components func: useEffect 1 ", error);
            }
          );
        }
      },
      (apierror) => {
        console.log("sessions-components func: useEffect 2 ", apierror);
      }
    );
  }, [currentForm]);

  useEffect(() => {
    const folder = searchParam.get("folder");
    displayFolder(parseInt(folder, 10));
  }, [folders]);

  const navigateToHomescreen = () => {
    navigate("/home", { replace: true });
  };

  const newRecording = () => {
    if (currentFolder !== "") {
      navigate("/sessions/new?folder=" + currentFolder, { replace: true });
    } else {
      navigate("/sessions/new", { replace: true });
    }
    //navigate('/sessions/new'+"?folder=", { queryParams: { folder: this.currentFolder } });
  };

  const goToSession = (session) => {
    navigate("/sessions/" + session.id);
  };

  // ----------
  // Folders
  // ----------

  const displayFolder = (folderId) => {
    if (!folderId) {
      setDisplayedFolders(folders.filter((f) => f.parent == null));
      setDisplayedSessions(sessions.filter((s) => s.folder == null));
      setBreadCrumbs([]);
      setCurrentFolder("");
      navigate("/sessions");
      // const url = '/sessions';
      // this.location.replaceState(url);
    } else {
      setDisplayedFolders(folders.filter((x) => x.parent === folderId));
      setDisplayedSessions(sessions.filter((s) => s.folder === folderId));
      setCurrentFolder(folderId);
      buildBreadcrumbs(folderId);
      setSearchParam({ folder: folderId }, { replace: true });
      // const url = '/sessions/?folder=' + folderId;
      // this.location.replaceState(url);
    }
  };

  const buildBreadcrumbs = (folderId) => {
    let folder = folders.find((f) => f.id === folderId);
    const bread = [];
    if (folder != null) {
      bread.unshift(folder);
      while (folder.parent) {
        folder = folders.find((f) => f.id === folder.parent);
        bread.unshift(folder);
      }
    }
    setBreadCrumbs(bread);
  };

  const buildBreadcrumbString = () => {
    if (breadcrumbs.length > 0) {
      const crumbnames = breadcrumbs.map((b) => b.name);
      crumbnames.unshift("Home");
      setFolderPath(crumbnames.join("/"));
    }
  };

  const goBackToPrevious = () => {
    if (breadcrumbs.length > 1) {
      displayFolder(breadcrumbs[breadcrumbs.length - 2].id);
    } else {
      displayFolder();
    }
  };

  const addFolder = (newName, locationId) => {
    if (!newName) {
      setShowAlert(true);
      setAlertMessage("Please enter folder name");
      closeDialog();
    } else {
      const fetchData = new SessionService().addFolder(newName, locationId);
      fetchData
        .then(
          (response) => {
            if (response.status === 200) {
              const folder = FolderModel.fromJson(response.json());
              folders.push(folder);
              if (locationId) {
                displayFolder(folder.parent);
              } else {
                displayFolder();
              }
            } else {
              setShowAlert(true);
              setAlertMessage(response.json()["message"]);
            }
          },
          (apierror) => {
            console.log("sessions-components func: addFolder 1 ", apierror);
          }
        )
        .finally(() => closeDialog());
    }
  };

  const changeFolderName = (newName) => {
    if (newName == "") {
      setInvalidName(true);
      return;
    }
    setInvalidName(false);
    setCurrentForm("Loading");
    const folderId = selectedFolder.id;
    const fetchData = new SessionService().updateFolder(
      folderId,
      null,
      newName
    );
    fetchData
      .then(
        (response) => {
          if (response.status === 200) {
            const folder = FolderModel.fromJson(response.json());
            const folderIndex = folders.findIndex((s) => s.id === folder.id);
            folders[folderIndex] = folder;
            displayFolder(folder.parent);
          } else {
            setShowAlert(true);
            setAlertMessage(response.json()["message"]);
          }
        },
        (apierror) => {
          console.log(
            "sessions-components func: changefoldername 1 ",
            apierror
          );
        }
      )
      .finally(() => {
        closeDialog();
      });
  };

  const moveFolder = (newFolderId) => {
    const fetchData = new SessionService().updateFolder(
      selectedFolder.id,
      newFolderId,
      null
    );
    fetchData
      .then(
        (response) => {
          if (response.status === 200) {
            const updatedFolder = FolderModel.fromJson(response.json());
            const index = folders.findIndex((f) => f.id === updatedFolder.id);
            folders[index] = updatedFolder;
            /* console.log("MOVE FOLDER");
          console.log(folders)
          console.log(updatedFolder);
          console.log(newFolderId); // ideally I'd want to change it to this thing
          const diffFolder = folders.findIndex(f => f.id === newFolderId); */
            // this might need to be changed
            displayFolder(updatedFolder.parent);
          } else {
            setShowAlert(true);
            setAlertMessage(response.json()["message"]);
          }
        },
        (apierror) => {
          console.log("sessions-components func: movefolder 1 ", apierror);
        }
      )
      .finally(() => {
        closeDialog();
      });
  };

  const deleteFolder = () => {
    setCurrentForm("Loading");
    const folderId = selectedFolder.id;
    const parentId = selectedFolder.parent;
    const fetchData = new SessionService().deleteFolder(folderId);
    fetchData
      .then(
        (response) => {
          if (response.status === 200) {
            //const updatedFolder = FolderModel.fromJson(response.json());
            const foldersToRemove = [folderId];
            const children = folders.filter((f) => f.parent === folderId);
            while (children.length > 0) {
              const child = children.pop();
              foldersToRemove.push(child.id);
              folders
                .filter((f) => f.parent === child.id)
                .forEach((f) => children.push(f));
            }
            setFolders(
              folders.filter((f) => foldersToRemove.indexOf(f.id) === -1)
            );
            setSessions(
              sessions.filter((s) => foldersToRemove.indexOf(s.folder) === -1)
            );
            if (parentId) {
              displayFolder(parentId);
            } else {
              displayFolder();
            }
          } else {
            setShowAlert(true);
            setAlertMessage(response.json()["message"]);
          }
        },
        (apierror) => {
          console.log("sessions-components func: movefolder 1 ", apierror);
        }
      )
      .finally(() => {
        closeDialog();
      });
  };

  // ----------
  // Sessions
  // ----------

  const endSession = (session) => {
    setCurrentForm("Loading");
    const sessionId = session.id;
    setSelectedSession(null);
    const fetchData = new SessionService().endSession(sessionId);
    fetchData
      .then(
        (response) => {
          if (response.status === 200) {
            const endedSession = SessionModel.fromJson(response.json());
            const sessionIndex = sessions.findIndex(
              (s) => s.id === endedSession.id
            );
            sessions[sessionIndex] = endedSession;
            displayFolder(endedSession.folder);
          } else {
            setShowAlert(true);
            setAlertMessage(response.json()["message"]);
          }
        },
        (apierror) => {
          console.log("sessions-components func: endsession 1 ", apierror);
        }
      )
      .finally(() => {
        closeDialog();
      });
  };

  const changeSessionName = (newName) => {
    if (newName == "") {
      setInvalidName(true);
      return;
    }
    setInvalidName(false);
    setCurrentForm("Loading");
    const sessionId = selectedSession.id;
    const fetchData = new SessionService().updateSession(sessionId, newName);
    fetchData.then(
      (response) => {
        if (response.status === 200) {
          console.log("CHANGING NAME");
          console.log(response);
          console.log(response.json());
          const session = SessionModel.fromJson(response.json());
          console.log(session);
          const sessionIndex = sessions.findIndex((s) => s.id === session.id);
          if (sessionIndex > -1) {
            sessions[sessionIndex] = session;
            displayFolder(session.folder);
          } else {
            setShowAlert(true);
            setAlertMessage(response.json()["message"]);
          }
        }
      },
      (apierror) => {
        console.log("sessions-components func:changesesion 1 ", apierror);
      }
    );
    closeDialog();
  };

  const moveSession = (newParentId) => {
    const fetchData = new SessionService().updateSessionFolder(
      selectedSession.id,
      newParentId
    );
    fetchData
      .then(
        (response) => {
          if (response.status === 200) {
            const updatedSession = SessionModel.fromJson(response.json());
            const index = sessions.findIndex((s) => s.id === updatedSession.id);
            sessions[index] = updatedSession;
            displayFolder(updatedSession.folder);
          } else {
            setShowAlert(true);
            setAlertMessage(response.json()["message"]);
          }
        },
        (apierror) => {
          console.log("sessions-components func:movesession 1 ", apierror);
        }
      )
      .finally(() => {
        closeDialog();
      });
  };

  const deleteSession = () => {
    setCurrentForm("Loading");
    const sessionId = selectedSession.id;
    const fetchData = new SessionService().deleteSession(sessionId);
    fetchData
      .then(
        (response) => {
          if (response.status === 200) {
            const parent = folders.find((f) => f.id === selectedSession.folder);
            setSessions(sessions.filter((s) => s.id !== sessionId));
          } else {
            setShowAlert(true);
            setAlertMessage(response.json()["message"]);
          }
        },
        (apierror) => {
          console.log("sessions-components func deletesession 1 ", apierror);
        }
      )
      .finally(() => {
        closeDialog();
      });
  };

  // ----------
  // Dialogs
  // ----------

  const openSessionDialog = (newForm, selectedSession) => {
    setCurrentForm(newForm);
    setSelectedSession(selectedSession);
    if (newForm === "MoveSession") {
      setSelectableFolders(folders);
    }
  };

  const openFolderDialog = (newForm, selectedFolder) => {
    setCurrentForm(newForm);
    setSelectedFolder(selectedFolder);
    if (newForm === "MoveFolder") {
      setSelectableFolders(
        folders.filter(
          (f) => f.parent !== selectedFolder.id && f.id !== selectedFolder.id
        )
      );
    }
  };

  const closeDialog = () => {
    setCurrentForm("");
    setSelectedSession(null);
    setSelectedFolder(null);
    setFolderSelect(null);
    setInvalidName(false);
  };

  const closeAlert = () => {
    setShowAlert(false);
  };

  return (
    <DiscussionSessionPage
      openFolderDialog={openFolderDialog}
      navigateToHomescreen={navigateToHomescreen}
      isLoading={isLoading}
      sessions={sessions}
      folders={folders}
      breadcrumbs={breadcrumbs}
      goBackToPrevious={goBackToPrevious}
      displayFolder={displayFolder}
      displayedFolders={displayedFolders}
      displayedSessions={displayedSessions}
      goToSession={goToSession}
      openSessionDialog={openSessionDialog}
      alertMessage={alertMessage}
      showAlert={showAlert}
      closeAlert={closeAlert}
      currentForm={currentForm}
      closeDialog={closeDialog}
      selectedSession={selectedSession}
      changeSessionName={changeSessionName}
      changeFolderName={changeFolderName}
      deleteSession={deleteSession}
      deleteFolder={deleteFolder}
      addFolder={addFolder}
      newRecording={newRecording}
      moveFolder={moveFolder}
      moveSession={moveSession}
      selectedFolder={selectedFolder}
      selectableFolders={selectableFolders}
      folderSelect={folderSelect}
      setFolderSelect={setFolderSelect}
      invalidName={invalidName}
    />
  );
}

export { SessionsComponent };

// client/src/app/sessions/sessions.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { SessionService } from '../services/session.service';
import 'rxjs/add/operator/finally';
import {Location} from '@angular/common';

enum Forms {
  RenameSession = 1,
  RenameFolder,
  DeleteSession,
  DeleteFolder,
  NewFolder,
  Loading,
  MoveSession,
  MoveFolder
}

@Component({
  selector: 'app-sessions',
  templateUrl: './sessions.component.html',
  styleUrls: ['./sessions.component.scss']
})
export class SessionsComponent implements OnInit {

  forms = Forms;
  currentForm: Forms = null;
  sessions: any[] = [];
  folders: any [] = [];
  displayedFolders: any [] = [];
  displayedSessions: any [] = [];
  selectableFolders: any[] = [];
  selectedSession: any;
  selectedFolder: any;
  isLoading = true;
  showAlert = false;
  alertMessage: string;
  breadcrumbs: any[] = [];
  currentFolder: any;
  folderPath: string;

  constructor(private router: Router,
              private sessionService: SessionService,
              private route: ActivatedRoute,
              private location: Location
              ) { }

  ngOnInit() {
    this.sessionService.getSessions().subscribe(sessions => {
      this.sessions = sessions;

      this.sessionService.getFolders().subscribe(folders => {
        this.folders = folders;
        console.log(folders, 'folders ...')
        this.route.queryParams.subscribe(params => {
          const folder = params['folder'];
          this.displayFolder(parseInt(folder, 10));
        });
      });
    });
    this.isLoading = false;
  }

  navigateToHomescreen() {
    this.router.navigate(['homescreen']);
  }

  newRecording() {
    this.router.navigate(['/sessions/new'], {queryParams: {folder: this.currentFolder}});
  }

  goToSession(session) {
    this.router.navigate(['/sessions/' + session.id]);
  }

  // ----------
  // Folders
  // ----------

  displayFolder(folderId?) {
    if (!folderId) {
      this.displayedFolders = this.folders.filter(f => f.parent == null);
      this.displayedSessions = this.sessions.filter(s => s.folder == null);
      this.breadcrumbs = [];
      this.currentFolder = undefined;
      const url = '/sessions';
      this.location.replaceState(url);
    } else {
      this.displayedFolders = this.folders.filter(x => x.parent === folderId);
      this.displayedSessions = this.sessions.filter(s => s.folder === folderId);
      this.currentFolder = folderId;
      this.buildBreadcrumbs(folderId);
      const url = '/sessions/?folder=' + folderId;
      this.location.replaceState(url);
    }
  }

  buildBreadcrumbs(folderId) {
    this.breadcrumbs = [];
    let folder = this.folders.find(f => f.id === folderId);
    if (folder != null) {
      this.breadcrumbs.unshift(folder);
      while (folder.parent) {
        folder = this.folders.find(f => f.id === folder.parent);
        this.breadcrumbs.unshift(folder);
      }
    }
  }

  buildBreadcrumbString() {
    if (this.breadcrumbs.length > 0) {
      const crumbnames = this.breadcrumbs.map(b => b.name);
      crumbnames.unshift('Home');
      this.folderPath = crumbnames.join('/');
    }
  }

  goBackToPrevious() {
    if (this.breadcrumbs.length > 1) {
      this.displayFolder(this.breadcrumbs[this.breadcrumbs.length - 2].id);
    } else {
      this.displayFolder();
    }
  }

  addFolder(newName: string, locationId: number) {
    if (!newName) {
      this.showAlert = true;
      this.alertMessage = 'Please enter folder name';
      this.closeDialog();
    } else {
      this.sessionService.addFolder(newName, locationId).finally(() => {
        this.closeDialog();
      }).subscribe(folder => {
        this.folders.push(folder);
        if (locationId) {
          this.displayFolder(folder.parent);
        } else {
          this.displayFolder();
        }
      }, error => {
        this.showAlert = true;
        this.alertMessage = error.json()['message'];
      });
    }
  }

  changeFolderName(newName: string) {
    this.currentForm = this.forms.Loading;
    const folderId = this.selectedFolder.id;
    this.sessionService.updateFolder(folderId, null, newName).finally(() => {
      this.closeDialog();
    }).subscribe(folder => {
      const folderIndex = this.folders.findIndex(s => s.id === folder.id);
      this.folders[folderIndex] = folder;
      this.displayFolder(folder.parent);
    }, error => {
      this.showAlert = true;
      this.alertMessage = error.json()['message'];
    });
  }

  moveFolder(newFolderId) {
    this.sessionService.updateFolder(this.selectedFolder.id, newFolderId, null).finally(() => {
      this.closeDialog();
    }).subscribe(updatedFolder => {
      const index = this.folders.findIndex(f => f.id === updatedFolder.id);
      this.folders[index] = updatedFolder;
      this.displayFolder(updatedFolder.parent);
    }, error => {
      this.showAlert = true;
      this.alertMessage = (error.json()['message']);
    });
  }

  deleteFolder() {
    this.currentForm = this.forms.Loading;
    const folderId = this.selectedFolder.id;
    const parentId = this.selectedFolder.parent;
    this.sessionService.deleteFolder(folderId).finally(() => {
      this.closeDialog();
    }).subscribe(() => {
      const foldersToRemove = [folderId];
      const children = this.folders.filter(f => f.parent === folderId);
      while (children.length > 0) {
        const child = children.pop();
        foldersToRemove.push(child.id);
        this.folders.filter(f => f.parent === child.id).forEach(f => children.push(f));
      }
      this.folders = this.folders.filter(f => foldersToRemove.indexOf(f.id) === -1);
      this.sessions = this.sessions.filter(s => foldersToRemove.indexOf(s.folder) === -1);
      if (parentId) {
        this.displayFolder(parentId);
      } else {
        this.displayFolder();
      }
    }, error => {
      this.showAlert = true;
      this.alertMessage = error.json()['message'];
    });
  }

  // ----------
  // Sessions
  // ----------

  endSession(session: any) {
    this.currentForm = this.forms.Loading;
    const sessionId = session.id;
    this.selectedSession = null;
    this.sessionService.endSession(sessionId).finally(() => {
      this.closeDialog();
    }).subscribe(endedSession => {
      const sessionIndex = this.sessions.findIndex(s => s.id === endedSession.id);
      this.sessions[sessionIndex] = endedSession;
      this.displayFolder(endedSession.folder);
    },
      error => {
        this.showAlert = true;
        this.alertMessage = error.json()['message'];
    });
  }

  changeSessionName(newName: string) {
    this.currentForm = this.forms.Loading;
    const sessionId = this.selectedSession.id;
    this.sessionService.updateSession(sessionId, newName).subscribe(session => {
      const sessionIndex = this.sessions.findIndex(s => s.id === session.id);
      if (sessionIndex > -1) {
        this.sessions[sessionIndex] = session;
    this.displayFolder(session.folder);
      }
    }, error => {
      this.showAlert = true;
      this.alertMessage = error.json()['message'];
    });
    this.closeDialog();
  }

  moveSession(newParentId) {
    this.sessionService.updateSessionFolder(this.selectedSession.id, newParentId).finally(() => {
      this.closeDialog();
    }).subscribe(updatedSession => {
      const index = this.sessions.findIndex(s => s.id === updatedSession.id);
      this.sessions[index] = updatedSession;
      this.displayFolder(updatedSession.folder);
    }, error => {
      this.showAlert = true;
      this.alertMessage = error.json()['message'];
    });
  }

  deleteSession() {
    this.currentForm = this.forms.Loading;
    const sessionId = this.selectedSession.id;
    this.sessionService.deleteSession(sessionId).finally(() => {
      this.closeDialog();
    }).subscribe(() => {
      const parent = this.folders.find(f => f.id === this.selectedSession.folder);
      this.sessions = this.sessions.filter(s => s.id !== sessionId);
      if (parent) {
        this.displayFolder(parent.id);
      } else {
        this.displayFolder();
      }
    }, error => {
      this.showAlert = true;
      this.alertMessage = error.json()['message'];
    });
  }

  // ----------
  // Dialogs
  // ----------

  openSessionDialog(newForm: any, selectedSession?: any) {
    this.currentForm = newForm;
    this.selectedSession = selectedSession;
    if (this.currentForm === Forms.MoveSession) {
      this.selectableFolders = this.folders;
    }
  }

  openFolderDialog(newForm: any, selectedFolder?: any) {
    this.currentForm = newForm;
    this.selectedFolder = selectedFolder;
    if (this.currentForm === Forms.MoveFolder) {
      this.selectableFolders = this.folders.filter(f => f.parent !== this.selectedFolder.id && f.id !== this.selectedFolder.id);
    }
  }

  closeDialog() {
    this.currentForm = null;
    this.selectedSession = null;
    this.selectedFolder = null;
  }

  closeAlert() {
    this.showAlert = false;
  }

  printdebug(tempVar){
    console.log(tempVar, 'debugging ...');

  }
}

<div class="container">
  <app-header [title]="'Manage Discussions'" (backClick)="navigateToHomescreen()"></app-header>
  <div class="list-container">
    <div *ngIf="isLoading" class="load-text">Loading...</div>
    <div *ngIf="!isLoading && sessions.length == 0  && folders.length == 0" class="empty-session-list">
      <div class="load-text"> No Discussions or Folders </div>
      <div class="load-text-description"> Tap the buttons below to record your first discussion or create your first folder. </div>
    </div>
    <!-- Breadcrumb -->
    <div class="breadcrumb-container">
      <div *ngIf="breadcrumbs.length > 0" (click)="goBackToPrevious()">
        <img src="../assets/img/icon-back.svg" class="breadcrumb-arrow-icon">
      </div>
      <span *ngIf="folders.length > 0">
        <span (click)="displayFolder()" class="crumb-name"> Home</span>
        <span *ngIf="breadcrumbs.length > 1" class="breadcrumbs"> / . . . / </span>
        <span *ngIf="breadcrumbs.length == 1" class="breadcrumbs"> / </span>
        <div *ngIf="breadcrumbs.length > 0" class="crumb-name">{{ breadcrumbs[breadcrumbs.length - 1].name}}</div>
      </span>
    </div>
    <!-- Folders -->
    <div *ngIf="!isLoading && displayedFolders.length > 0">
      <ul class="list">
        <li *ngFor="let folder of displayedFolders" class="folder-item">
          <img src="../assets/img/folder.svg" class="folder-icon">
          <div class="folder-title" (click)="displayFolder(folder.id)">{{folder.name}}</div>
          <div class="folder-options">
            <app-context-menu>
              <div class="menu-item" (click)="openFolderDialog(forms.RenameFolder, folder)">Edit Name</div>
              <div class="menu-item" (click)="openFolderDialog(forms.MoveFolder, folder)"> Move To...</div>
              <div  class="menu-item red" (click)="openFolderDialog(forms.DeleteFolder, folder)">Delete</div>
            </app-context-menu>
          </div>
        </li>
      </ul>
    </div>
    <!-- Sessions -->
    <div *ngIf="!isLoading && displayedSessions.length > 0">
      <ul class="list">
        <li *ngFor="let session of displayedSessions" class="session-item">
          <svg x="0" y="0" width="24" height="24" viewBox="0 0 20 30" class="session-icon" [class.active-session]="session.recording">
              <use xlink:href="../assets/img/mic.svg#5"></use>
          </svg>
          <div class="click-mask" (click)="goToSession(session)"></div>
          <div class="session-title">{{session.title}}</div>
          <div class="session-date">{{session.formattedDate}}</div>
          <div class="session-options">
            <app-context-menu>
              <div class="menu-item" (click)="openSessionDialog(forms.RenameSession, session)">Edit Name</div>
              <div class="menu-item" (click)="openSessionDialog(forms.MoveSession, session)"> Move To...</div>
              <div *ngIf="!session.recording" class="menu-item red" (click)="openSessionDialog(forms.DeleteSession, session)">Delete</div>
              <div *ngIf="session.recording" class="menu-item red" (click)="endSession(session)">End</div>
              </app-context-menu>
            </div>
          <div class="session-title">{{session.name}}</div>
        </li>
      </ul>
    </div>
    <div *ngIf="folders.length > 0 || sessions.length > 0">
      <div *ngIf="displayedFolders.length == 0 && displayedSessions.length == 0">
        <div class="folder-empty"> Folder Empty </div>
      </div>
    </div>
  </div>
  <button class="basic-button medium-button" (click)="openFolderDialog(forms.NewFolder)">New Folder</button>
  <button class="basic-button medium-button" (click)="newRecording()">New Discussion</button>
</div>

<app-dialog *ngIf="currentForm" (closeDialog)="closeDialog()">
  <!-- Update Session Name -->
  <div *ngIf="currentForm == forms.RenameSession" class="dialog-window">
    <div class="dialog-heading">Update Discussion Name:</div>
    <input #txtName [value]="selectedSession.title" class="field-input" maxlength="64">
    <button class="basic-button" (click)="changeSessionName(txtName.value)">Confirm</button>
    <button class="cancel-button" (click)="closeDialog()">Cancel</button>
  </div>

  <!-- Update Folder Name -->
  <div *ngIf="currentForm == forms.RenameFolder" class="dialog-window">
    <div class="dialog-heading">Update Folder Name:</div>
    <input #txtName [value]="selectedFolder.name" class="field-input" maxlength="64">
    <button class="basic-button" (click)="changeFolderName(txtName.value)">Confirm</button>
    <button class="cancel-button" (click)="closeDialog()">Cancel</button>
  </div>

  <!-- Delete Session -->
  <div *ngIf="currentForm == forms.DeleteSession" class="dialog-window">
    <div class="dialog-heading">Delete Session</div>
    <div class="dialog-body">Are you sure you want to permanently delete this session?</div>
    <button class="delete-button" (click)="deleteSession()">Delete</button>
    <button class="cancel-button" (click)="closeDialog()">Cancel</button>
  </div>

    <!-- Delete Folder -->
  <div *ngIf="currentForm == forms.DeleteFolder" class="dialog-window">
    <div class="dialog-heading"> Delete Folder</div>
    <div class="dialog-body"> Are you sure you want to permanently delete this folder and all of its contents?</div>
    <button class="delete-button" (click)="deleteFolder()">Delete</button>
    <button class="cancel-button" (click)="closeDialog()">Cancel</button>
  </div>

  <!-- Add Folder -->
  <div *ngIf="currentForm == forms.NewFolder" class="dialog-window">
    <div class="dialog-heading"> Add New Folder</div>
    <input placeholder="Enter new file name" #txtName [value] class="field-input" maxlength="64">
    <div *ngIf="!breadcrumbs.length > 0" class="basic-button" (click)="addFolder(txtName.value, null)">Confirm</div>
    <div *ngIf="breadcrumbs.length > 0" class="basic-button" (click)="addFolder(txtName.value,breadcrumbs[breadcrumbs.length - 1].id)"> Confirm</div>
    <button class="cancel-button" (click)="closeDialog()">Cancel</button>
  </div>

  <!-- Move Folder -->
  <div *ngIf="currentForm == forms.MoveFolder" class="dialog-window">
    <div class="dialog-heading">Move Folder</div>
    <app-folder-select #folderSelect [folders]="selectableFolders" (click)= "printdebug(folderSelect.folder)"></app-folder-select>
    <button *ngIf="folderSelect.folder" class="basic-button" (click)="moveFolder(folderSelect.folder)">OK</button>
    <button class="cancel-button" (click)="closeDialog()">Cancel</button>
  </div>

  <!-- Move Session -->
  <div *ngIf="currentForm == forms.MoveSession" class="dialog-window">
    <div class="dialog-heading">Move Discussion</div>
    <app-folder-select #folderSelect [folders]="selectableFolders"></app-folder-select>
    <button *ngIf="folderSelect.folder" class="basic-button" (click)="moveSession(folderSelect.folder)">OK</button>
    <button class="cancel-button" (click)="closeDialog()">Cancel</button>
  </div>

  <!-- Loading -->
  <div *ngIf="currentForm == forms.Loading" class="dialog-window">
    <div class="dialog-heading">Loading...please wait...</div>
  </div>
</app-dialog>

<!--Alerts -->
<app-dialog *ngIf="showAlert">
  <div>
    <div class="dialog-heading">Error</div>
      <div class=add-dialog>
        {{alertMessage}}
      <button class="cancel-button" (click)="closeAlert()">Close</button>
    </div>
  </div>
</app-dialog>
