// frontend/src/keywords/keywords-component.jsx
import { TranscriptModel } from '../models/transcript';
import { formatSeconds, similarityToRGB } from '../globals';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {AppKeywordsPage} from './html-pages'


function AppKeywordsComponent(props) {
  const [displayKeywords, setDisplayKeywords] = useState([]);
  const [showGraph, setShowGraph] = useState(false);
  const [keywordPoints, setKeywordPoints] = useState();
  const [timelineWidth, setTimeLineWidth] = useState(240);
  const [_start, setStart] = useState(props.start);
  const [_end, setEnd]  = useState(props.end);
  const [callbackfunc, setCallbackFunc] = useState();
  const [showDialog, setShowDialog] = useState(false);
  const [reload, setReload] = useState(false);
  const navigate = useNavigate()

  
  useEffect(()=>{
  refresh()
  if(props.transcripts.length > 0){
    setReload(true)
  }
  },[props.transcripts])

  const toggleGraph = ()=> {
    setShowGraph(!showGraph);
    refresh();
  }
  
  const toggleDisplay = (show)=> {
        setShowDialog(show);
  }

  const refresh = ()=> {
    if (showGraph) {
      refreshTimeline();
    } else {
      refreshKeywords();
    }
  }

  // --------
  // Text
  // --------

  const refreshKeywords = ()=> {
    const dispKeyword = [];
    for (const transcript of props.transcripts) {
      const words = new Set(transcript.keywords.map(k => k.word));
      words.forEach(word => {
        const highestSimilarity = Math.max(...transcript.keywords.filter(k => k.word === word).map(k => k.similarity));
        dispKeyword.push({'word': word, 'color': similarityToRGB(highestSimilarity), 'transcript_id': transcript.id});
      });
    }
    setDisplayKeywords(dispKeyword.reverse());
  }

  const showKeywordContext = (transcriptId)=> {
    if(props.fromclient){
      props.clickedKeyword(transcriptId)
    }else{
      navigate('/sessions/'+props.session.id+ '/pods/'+props.sessionDevice.id+ '/transcripts?index='+transcriptId);
    }
  }

  // --------
  // Graph
  // --------

  const refreshTimeline = ()=> {
    setKeywordPoints({});
    for (const keyword of props.session.keywords) {
      keywordPoints[keyword] = [];
    }

    for (const transcript of props.transcripts) {
      const duration = _end - _start;
      const keywordTracker = {};
      for (const keywordUsage of transcript.keywords) {
        const transcriptText = transcript.transcript;
        const word = keywordUsage.word;
        if (keywordUsage.word in keywordTracker) {
          keywordTracker[keywordUsage.word]++;
        } else {
          keywordTracker[keywordUsage.word] = 0;
        }
        const keywordIndex = keywordTracker[keywordUsage.word];
        const tPos = (transcriptText.indexOf(word, keywordIndex) / transcriptText.length) * transcript.length;
        const pos = (((transcript.start_time + tPos) - _start) / duration) * timelineWidth;
        keywordPoints[keywordUsage.keyword].push({
          'x': pos,
          'color': similarityToRGB(keywordUsage.similarity),
          'transcript_id': transcript.id
        });
      }
    }
  }

  const getSubstringIndex = (str, substring, n) =>{
    let times = 0, index = null;

    while (times < n && index !== -1) {
        index = str.indexOf(substring, index + 1);
        times++;
    }

    return index;
  }

  return (
    <AppKeywordsPage
        showGraph = {showGraph}
        displayKeywords = {displayKeywords}
        showKeywordContext = {showKeywordContext}
        session = {props.session}
        keywordPoints = {keywordPoints}
        callbackfunc = {callbackfunc}
        setCallbackFunc = {setCallbackFunc}
        toggleGraph = {toggleGraph}
        toggleDisplay = {toggleDisplay}
        showDialog = {showDialog}
    />
  )
}

export {AppKeywordsComponent}

// client/src/app/keywords/keywords.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Router } from '@angular/router';
import { Observable } from 'rxjs/Observable';
import { SessionModel } from '../models/session';
import { SessionDeviceModel } from '../models/session-device';
import { TranscriptModel } from '../models/transcript';
import { formatSeconds, similarityToRGB } from '../globals';

@Component({
  selector: 'app-keywords',
  templateUrl: './keywords.component.html',
  styleUrls: ['./keywords.component.scss']
})
export class KeywordsComponent {
  _transcripts: TranscriptModel[] = [];
  displayKeywords = [];
  showGraph = false;
  keywordPoints: any;
  timelineWidth = 240;
  _start: number;
  _end: number;

  @Input('session') session: SessionModel;
  @Input('sessionDevice') sessionDevice: SessionDeviceModel;
  @Input('transcripts')
  set setTranscripts(value: any) {
    this._transcripts = value;
    this.refresh();
  }
  @Input('start')
  set setStart(value: any) {
    this._start = value;
    this.refresh();
  }
  @Input('end')
  set setEnd(value: any) {
    this._end = value;
    this.refresh();
  }

  constructor(private router: Router) {}

  toggleGraph() {
    this.showGraph = !this.showGraph;
    this.refresh();
  }

  refresh() {
    if (this.showGraph) {
      this.refreshTimeline();
    } else {
      this.refreshKeywords();
    }
  }

  // --------
  // Text
  // --------

  refreshKeywords() {
    this.displayKeywords = [];
    for (const transcript of this._transcripts) {
      const words = new Set(transcript.keywords.map(k => k.word));
      words.forEach(word => {
        const highestSimilarity = Math.max(...transcript.keywords.filter(k => k.word === word).map(k => k.similarity));
        this.displayKeywords.push({'word': word, 'color': similarityToRGB(highestSimilarity), 'transcript_id': transcript.id});
      });
    }
  }

  showKeywordContext(transcriptId: any) {
    this.router.navigate(['sessions', this.session.id, 'pods', this.sessionDevice.id, 'transcripts'], {queryParams: {index: transcriptId}});
  }

  // --------
  // Graph
  // --------

  refreshTimeline() {
    this.keywordPoints = {};
    for (const keyword of this.session.keywords) {
      this.keywordPoints[keyword] = [];
    }

    for (const transcript of this._transcripts) {
      const duration = this._end - this._start;
      const keywordTracker = {};
      for (const keywordUsage of transcript.keywords) {
        const transcriptText = transcript.transcript;
        const word = keywordUsage.word;
        if (keywordUsage.word in keywordTracker) {
          keywordTracker[keywordUsage.word]++;
        } else {
          keywordTracker[keywordUsage.word] = 0;
        }
        const keywordIndex = keywordTracker[keywordUsage.word];
        const tPos = (transcriptText.indexOf(word, keywordIndex) / transcriptText.length) * transcript.length;
        const pos = (((transcript.start_time + tPos) - this._start) / duration) * this.timelineWidth;
        this.keywordPoints[keywordUsage.keyword].push({
          'x': pos,
          'color': similarityToRGB(keywordUsage.similarity),
          'transcript_id': transcript.id
        });
      }
    }
  }

  getSubstringIndex(str, substring, n) {
    let times = 0, index = null;

    while (times < n && index !== -1) {
        index = str.indexOf(substring, index + 1);
        times++;
    }

    return index;
  }
}


<div class="keyword-container">
  <ng-container *ngIf="!showGraph">
    <span *ngFor="let displayKeyword of displayKeywords; let last = last" class="keyword" [style.color]="displayKeyword.color" (click)="showKeywordContext(displayKeyword.transcript_id)">
      {{displayKeyword.word}}
      <span *ngIf="!last" class="base">, </span>
    </span>
    <div *ngIf="displayKeywords.length == 0" class="no-keywords">No keywords detected</div>
  </ng-container>

  <ng-container *ngIf="showGraph">
    <div class="timeline-container">
      <div class="keyword-timeline" *ngFor="let keyword of session.keywords">
        <div class="keyword-text">{{keyword}}</div>
        <div class="keyword-graph">
          <hr>
          <div *ngFor="let point of keywordPoints[keyword]" class="keyword-point" [style.left]="point.x + 'px'" [style.background-color]="point.color" (click)="showKeywordContext(point.transcript_id)"></div>
        </div>
      </div>
    </div>
    <div *ngIf="session.keywords.length == 0" class="no-keywords">No keywords detected</div>
  </ng-container>

  <div class="graph-menu">
    <app-context-menu #graphMenu>
      <div class="menu-item" (click)="toggleGraph(); graphMenu.toggle(false);">{{(showGraph)? 'Show Words': 'Show Timeline'}}</div>
    </app-context-menu>
  </div>
</div>
